/**
 * POS-only image catalogue. These assets are deliberately separate from
 * publicMeals so using them cannot change the website or subscriber menu.
 */
const POS_MEAL_IMAGES: Record<string, string> = {
  "": "Mongolian Beef Noodles.webp",
  "ADRENALINE BEEF BURGER": "Adrenaline Beef Burger.webp",
  "ADRENALINE SNICKERS": "Adrenaline Snickers.webp",
  "BASBOUSA COCONUT": "Basbousa Coconut.webp",
  "BASBOUSA PISTACHIO": "Basbousa Pistachio.webp",
  "BEEF ALFREDO": "Beef Alfredo.webp",
  "BEEF BURGER": "Beef Burger.webp",
  "BEEF FAJITA SANDWICH": "Beef Fajita Sandwich.webp",
  "BEEF KOFTA DELIGHT": "Beef Kofta Delight.webp",
  "BEEF KOFTA SAFFRON RICE": "Beef Kofta Saffron Rice.webp",
  "BEEF SHAWARMA": "Beef Shawarma.webp",
  "BEEF SHAWARMA BEETROOT RICE": "Beef Shawarma  with Beetroot Rice شاورما لحم البقر مع أرز الشمندر.jpg",
  "BEEF SHAWARMA WITH BEETROOT RICE": "Beef Shawarma with Beetroot Rice.webp",
  "BEEF STROGANOFF": "Beef Stroganoff.webp",
  "BEETROOT SALAD": "Beetroot Salad.webp",
  "BEETROOT SHOT": "Beetroot Shot.webp",
  "BROWNIES": "Brownies.webp",
  "BUFFALO CHICKEN WRAP": "Buffalo Chicken Wrap.webp",
  "CHICKEN ALFREDO PASTA": "Chicken Alfredo دجاج ألفريدو.jpg",
  "CHICKEN AVOCADO SANDWICH": "Chicken Avocado Sandwich.webp",
  "CHICKEN CURRY": "Chicken Curry.webp",
  "CHICKEN FAJITA SANDWICH": "Chicken Fajita Sandwich.webp",
  "CHICKEN RISOTTO": "Chicken Risotto.webp",
  "CHICKEN SHAWARMA": "Chicken Shawarma.webp",
  "CHICKEN STROGANOFF": "Chicken Stroganoff.webp",
  "CHICKEN TACOS": "Chicken Tacos.webp",
  "CLASSIC FATTOUSH SALAD": "Classic Fattoush Salad.webp",
  "COOKIES": "Cookies.webp",
  "CORDON BLEU": "Cordon Bleu.webp",
  "CRAB SALAD": "Crab Salad.webp",
  "CRISPY CHICKEN BURGER": "Crispy Chicken Burger.webp",
  "DETOX SHOT": "Detox Shot.webp",
  "DYNAMITE SHRIMP": "Dynamite Shrimp.webp",
  "EGG AVOCADO TOAST": "Egg Avocado Toast.webp",
  "EGG MUFFIN": "Egg Muffin.webp",
  "ENERGY BALLS 3PCS": "Energy Balls 3pcs.webp",
  "FALAFEL WRAP": "Falafel Wrap.webp",
  "FALAFIL WRAP": "Falafal Wrap لفافة الفلافل.jpg",
  "FRENCH TOAST": "French Toast.webp",
  "FRESH MANDARIN WITH POMEGRANATE": "Fresh Mandarin with Pomegranate.webp",
  "FRESH ORANGE JUICE": "Fresh Orange Juice.webp",
  "FRESH PINEAPPLE CUT": "Fresh Pineapple Cut.webp",
  "GATHERING BOX BURGERS": "Gathering Box Burgers.webp",
  "GATHERING BOX SANDWICHES": "Gathering Box Sandwiches.webp",
  "GATHERING BOX SUB SANDWICHES": "Gathering Box Sub Sandwiches.webp",
  "GATHERING BOX TACOS": "Gathering Box Tacos.webp",
  "GREEK CHICKEN": "Greek Chicken.webp",
  "GREEK INFUSION": "Greek Infusion.webp",
  "GRILLED CHICKEN 100G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 150G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 200G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 250G": "Grilled Chicken 100g.webp",
  "GRILLED STEAK 100G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 150G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 200G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 250G": "Grilled Steak 100g.webp",
  "HALLOUMI PESTO SANDWICH": "Halloumi Pesto Sandwich.webp",
  "HAZELNUT LAVA CAKE": "Hazelnut Lava Cake.webp",
  "HEALTHY CHICKEN MAJBOOS": "Healthy Chicken Majboos.webp",
  "HEAVEN BALL": "Heaven Ball.webp",
  "IRANIAN KOFTA": "Iranian Kofta.webp",
  "KUNAFA PISTACHIO BALLS": "Kunafa Pistachio Balls.webp",
  "LENTIL SOUP": "Lentil Soup.webp",
  "MASHED POTATO 100G": "Mashed Potato 100g.webp",
  "MASHED POTATO 150G": "Mashed Potato 100g.webp",
  "MASHED POTATO 200G": "Mashed Potato 100g.webp",
  "MASHED POTATO 250G": "Mashed Potato 100g.webp",
  "MASHED SWEET POTATO 100G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 150G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 200G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 250G": "Mashed Sweet Potato 100g.webp",
  "MATCHA CHEESECAKE": "Matcha Cheesecake.webp",
  "MATCHA GLOW JUICE": "Matcha Glow Juice.webp",
  "MEDITERRANEEN FETA SALAD": "Mediterraneen Feta Salad.webp",
  "MIX POMEGRANATE PINEAPPLE": "Mix Pomegranate&pineapple.webp",
  "MIX STRAWBERRY BLUEBERRY": "Mix Strawberry & Blueberry.webp",
  "MONGOLIAN BEEF NOODLES": "Mongolian Beef Noodles.webp",
  "MONGOLIAN BEEF WITH NOODLES": "Mongolia Beef Noodles نودلز لحم البقر المنغولي.jpg",
  "ORIENTAL BREAKFAST": "Oriental Breakfast.webp",
  "OXYGEN CHIPS CHIPOTLE CHILLI": "Oxygen Chips Chipotle Chili.webp",
  "OXYGEN CHIPS SALTED VINEGAR": "Oxygen Chips Salted Vinegar.webp",
  "OXYGEN CHIPS SWEET CHILLI PEPPER": "Oxygen Chips Sweet Chili Pepper.webp",
  "OXYGEN CHIPS SWEET HONEY BBQ": "Oxygen Chips Hot Honey BBQ.webp",
  "PECAN CARAMEL CHEESECAKE": "Pecan Caramel Cheesecake.webp",
  "PECAN WITH CHOCOLATE": "Pecan with Chocolate.webp",
  "PEPPERONI PIZZA": "Pepperoni Pizza.webp",
  "PISTACHIO LAVA CAKE": "Pistachio Lava Cake.webp",
  "PISTACHIO SALAD": "Pistachio Salad.webp",
  "PIZZA SLICE PEPPERONI": "Pizza Slice Pepperoni.webp",
  "PIZZA SLICE VEGGIE": "Pizza Slice Veggie.webp",
  "POMEGRANATE": "Pomegranate.webp",
  "POWER BALL": "Power Ball.webp",
  "PROTEIN LAVA CAKE": "Protein Lava Cake.webp",
  "PROTEIN LAZY CAKE": "PROTEIN LAZY CAKE.webp",
  "RASPBERRY RICE PUDDING": "Raspberry Rice Pudding.webp",
  "RICE 100G": "Rice 100g.webp",
  "RICE 150G": "Rice 100g.webp",
  "RICE 200G": "Rice 100g.webp",
  "RICE 250G": "Rice 100g.webp",
  "RICE PUDDING": "Rice Pudding.webp",
  "SALMON CURRY": "Salmon Curry.webp",
  "SHAKSHOUKA": "Shakshouka.webp",
  "SHISHTAWOOK SANDWICH": "Shishtawook Sandwich.webp",
  "STEAK SANDWICH": "Steak Sandwich.webp",
  "SWEET POTATO DELIGHT": "Sweet Potato Delight.webp",
  "SWEET POTATO ENERGY BOOSTER": "Sweet Potato Energy Booster.webp",
  "TALBINA MAJDOUL": "Talbina Majdoul.webp",
  "TARTE": "Tarte.webp",
  "TIRAMISU": "Tiramisu.webp",
  "TUNA SANDWICH": "Tuna Sandwich.webp",
  "UMMALI": "Ummali.webp",
  "VANILLA MUFFIN": "Vanilla Muffin.webp",
  "VEGAN AVOCADO TOAST": "Vegan Avocado Toast.webp",
  "VEGGIE PIZZA": "Veggie Pizza.webp",
  "VITARGO DRINK MANGO FLAVOUR": "Vitargo Drink-mango Flavour.webp",
  "VITARGO DRINK ORANGE FLAVOUR": "Vitargo Drink-orange Flavour.webp",
  "VITARGO DRINK RASPBERRY FLAVOUR": "Vitargo Drink-raspberry Flavour.webp",
  "WATER ALKALINE 500ML": "Alka Live Water 500ml.webp",
  "WATER ALKALINE SMALL": "Alka Live Water 500ml.webp",
  "ZAATAR OMLETTE": "Zaatar Omlette.webp",
  "ZUCHINI PASTA": "Zuchini Pasta.webp",
};

function normalizeMealName(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .toUpperCase();
}

export function getPosMealImage(...names: Array<string | null | undefined>) {
  for (const name of names) {
    if (!name) continue;
    const filename = POS_MEAL_IMAGES[normalizeMealName(name)];
    if (filename) {
      const thumbnail = filename.replace(/\.[^.]+$/, ".webp");
      return `/pos-meals/thumbs/${encodeURIComponent(thumbnail)}`;
    }
  }
  return null;
}
