/**
 * POS-only image catalogue. These assets are deliberately separate from
 * publicMeals so using them cannot change the website or subscriber menu.
 */
const POS_MEAL_IMAGES: Record<string, string> = {
  "": "Mongolian Beef Noodles.webp",
  "ADRENALINE BEEF BURGER": "Adrenaline Beef Burger.webp",
  "ADRENALINE SNICKERS": "Adrenaline Snickers.webp",
  "BASBOUSA COCONUT": "Basbousa Coconut.webp",
  "BASBOUSA PISTACHIO": "Basbousa Pistachio.webp",
  "BEEF ALFREDO": "Beef Alfredo.webp",
  "BEEF BURGER": "Beef Burger.webp",
  "BEEF FAJITA SANDWICH": "Beef Fajita Sandwich.webp",
  "BEEF KOFTA DELIGHT": "Beef Kofta Delight.webp",
  "BEEF KOFTA SAFFRON RICE": "Beef Kofta Saffron Rice.webp",
  "BEEF SHAWARMA": "Beef Shawarma.webp",
  "BEEF SHAWARMA BEETROOT RICE": "Beef Shawarma  with Beetroot Rice شاورما لحم البقر مع أرز الشمندر.jpg",
  "BEEF SHAWARMA WITH BEETROOT RICE": "Beef Shawarma with Beetroot Rice.webp",
  "BEEF STROGANOFF": "Beef Stroganoff.webp",
  "BEETROOT SALAD": "Beetroot Salad.webp",
  "BEETROOT SHOT": "Beetroot Shot.webp",
  "BROWNIES": "Brownies.webp",
  "BUFFALO CHICKEN WRAP": "Buffalo Chicken Wrap.webp",
  "CHICKEN ALFREDO PASTA": "Chicken Alfredo دجاج ألفريدو.jpg",
  "CHICKEN AVOCADO SANDWICH": "Chicken Avocado Sandwich.webp",
  "CHICKEN CURRY": "Chicken Curry.webp",
  "CHICKEN FAJITA SANDWICH": "Chicken Fajita Sandwich.webp",
  "CHICKEN RISOTTO": "Chicken Risotto.webp",
  "CHICKEN SHAWARMA": "Chicken Shawarma.webp",
  "CHICKEN STROGANOFF": "Chicken Stroganoff.webp",
  "CHICKEN TACOS": "Chicken Tacos.webp",
  "CLASSIC FATTOUSH SALAD": "Classic Fattoush Salad.webp",
  "COOKIES": "Cookies.webp",
  "CORDON BLEU": "Cordon Bleu.webp",
  "CRAB SALAD": "Crab Salad.webp",
  "CRISPY CHICKEN BURGER": "Crispy Chicken Burger.webp",
  "DETOX SHOT": "Detox Shot.webp",
  "DYNAMITE SHRIMP": "Dynamite Shrimp.webp",
  "EGG AVOCADO TOAST": "Egg Avocado Toast.webp",
  "EGG MUFFIN": "Egg Muffin.webp",
  "ENERGY BALLS 3PCS": "Energy Balls 3pcs.webp",
  "FALAFEL WRAP": "Falafel Wrap.webp",
  "FALAFIL WRAP": "Falafal Wrap لفافة الفلافل.jpg",
  "FRENCH TOAST": "French Toast.webp",
  "FRESH MANDARIN WITH POMEGRANATE": "Fresh Mandarin with Pomegranate.webp",
  "FRESH ORANGE JUICE": "Fresh Orange Juice.webp",
  "FRESH PINEAPPLE CUT": "Fresh Pineapple Cut.webp",
  "GATHERING BOX BURGERS": "Gathering Box Burgers.webp",
  "GATHERING BOX SANDWICHES": "Gathering Box Sandwiches.webp",
  "GATHERING BOX SUB SANDWICHES": "Gathering Box Sub Sandwiches.webp",
  "GATHERING BOX TACOS": "Gathering Box Tacos.webp",
  "GREEK CHICKEN": "Greek Chicken.webp",
  "GREEK INFUSION": "Greek Infusion.webp",
  "GRILLED CHICKEN 100G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 150G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 200G": "Grilled Chicken 100g.webp",
  "GRILLED CHICKEN 250G": "Grilled Chicken 100g.webp",
  "GRILLED STEAK 100G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 150G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 200G": "Grilled Steak 100g.webp",
  "GRILLED STEAK 250G": "Grilled Steak 100g.webp",
  "HALLOUMI PESTO SANDWICH": "Halloumi Pesto Sandwich.webp",
  "HAZELNUT LAVA CAKE": "Hazelnut Lava Cake.webp",
  "HEALTHY CHICKEN MAJBOOS": "Healthy Chicken Majboos.webp",
  "HEAVEN BALL": "Heaven Ball.webp",
  "IRANIAN KOFTA": "Iranian Kofta.webp",
  "KUNAFA PISTACHIO BALLS": "Kunafa Pistachio Balls.webp",
  "LENTIL SOUP": "Lentil Soup.webp",
  "MASHED POTATO 100G": "Mashed Potato 100g.webp",
  "MASHED POTATO 150G": "Mashed Potato 100g.webp",
  "MASHED POTATO 200G": "Mashed Potato 100g.webp",
  "MASHED POTATO 250G": "Mashed Potato 100g.webp",
  "MASHED SWEET POTATO 100G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 150G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 200G": "Mashed Sweet Potato 100g.webp",
  "MASHED SWEET POTATO 250G": "Mashed Sweet Potato 100g.webp",
  "MATCHA CHEESECAKE": "Matcha Cheesecake.webp",
  "MATCHA GLOW JUICE": "Matcha Glow Juice.webp",
  "MEDITERRANEEN FETA SALAD": "Mediterraneen Feta Salad.webp",
  "MIX POMEGRANATE PINEAPPLE": "Mix Pomegranate&pineapple.webp",
  "MIX STRAWBERRY BLUEBERRY": "Mix Strawberry & Blueberry.webp",
  "MONGOLIAN BEEF NOODLES": "Mongolian Beef Noodles.webp",
  "MONGOLIAN BEEF WITH NOODLES": "Mongolia Beef Noodles نودلز لحم البقر المنغولي.jpg",
  "ORIENTAL BREAKFAST": "Oriental Breakfast.webp",
  "OXYGEN CHIPS CHIPOTLE CHILLI": "Oxygen Chips Chipotle Chili.webp",
  "OXYGEN CHIPS SALTED VINEGAR": "Oxygen Chips Salted Vinegar.webp",
  "OXYGEN CHIPS SWEET CHILLI PEPPER": "Oxygen Chips Sweet Chili Pepper.webp",
  "OXYGEN CHIPS SWEET HONEY BBQ": "Oxygen Chips Hot Honey BBQ.webp",
  "PECAN CARAMEL CHEESECAKE": "Pecan Caramel Cheesecake.webp",
  "PECAN WITH CHOCOLATE": "Pecan with Chocolate.webp",
  "PEPPERONI PIZZA": "Pepperoni Pizza.webp",
  "PISTACHIO LAVA CAKE": "Pistachio Lava Cake.webp",
  "PISTACHIO SALAD": "Pistachio Salad.webp",
  "PIZZA SLICE PEPPERONI": "Pizza Slice Pepperoni.webp",
  "PIZZA SLICE VEGGIE": "Pizza Slice Veggie.webp",
  "POMEGRANATE": "Pomegranate.webp",
  "POWER BALL": "Power Ball.webp",
  "PROTEIN LAVA CAKE": "Protein Lava Cake.webp",
  "PROTEIN LAZY CAKE": "PROTEIN LAZY CAKE.webp",
  "RASPBERRY RICE PUDDING": "Raspberry Rice Pudding.webp",
  "RICE 100G": "Rice 100g.webp",
  "RICE 150G": "Rice 100g.webp",
  "RICE 200G": "Rice 100g.webp",
  "RICE 250G": "Rice 100g.webp",
  "RICE PUDDING": "Rice Pudding.webp",
  "SALMON CURRY": "Salmon Curry.webp",
  "SHAKSHOUKA": "Shakshouka.webp",
  "SHISHTAWOOK SANDWICH": "Shishtawook Sandwich.webp",
  "STEAK SANDWICH": "Steak Sandwich.webp",
  "SWEET POTATO DELIGHT": "Sweet Potato Delight.webp",
  "SWEET POTATO ENERGY BOOSTER": "Sweet Potato Energy Booster.webp",
  "TALBINA MAJDOUL": "Talbina Majdoul.webp",
  "TARTE": "Tarte.webp",
  "TIRAMISU": "Tiramisu.webp",
  "TUNA SANDWICH": "Tuna Sandwich.webp",
  "UMMALI": "Ummali.webp",
  "VANILLA MUFFIN": "Vanilla Muffin.webp",
  "VEGAN AVOCADO TOAST": "Vegan Avocado Toast.webp",
  "VEGGIE PIZZA": "Veggie Pizza.webp",
  "VITARGO DRINK MANGO FLAVOUR": "Vitargo Drink-mango Flavour.webp",
  "VITARGO DRINK ORANGE FLAVOUR": "Vitargo Drink-orange Flavour.webp",
  "VITARGO DRINK RASPBERRY FLAVOUR": "Vitargo Drink-raspberry Flavour.webp",
  "WATER ALKALINE 500ML": "Alka Live Water 500ml.webp",
  "WATER ALKALINE SMALL": "Alka Live Water 500ml.webp",
  "ZAATAR OMLETTE": "Zaatar Omlette.webp",
  "ZUCHINI PASTA": "Zuchini Pasta.webp",
  "IMMUNE SHOT": "Immune Shot.webp",
  "GOLDEN": "Golden Shot.webp",
  "DETOX": "Detox Shot.webp",
};

/** خريطة بالمعرّف: لا تنكسر عند إعادة تسمية الوجبة (أُعيدت تسمية 109 وجبات في 2026-09-15). */
export const POS_MEAL_IMAGES_BY_ID: Record<string, string> = {
  "kh7015dvtfzmb87fdzgr2f1eg98as6dz": "Egg Avocado Toast.webp",
  "kh70bcfw874nj88z4hfcz3qjwx8aswx5": "Golden Shot.webp",
  "kh70hmj8hapv8z7gvrpwg56p1s8aj9rg": "Vitargo Drink-raspberry Flavour.webp",
  "kh70msyb4q3ya944mh3sbak5898ajtc5": "Beetroot Shot.webp",
  "kh714vggr8sfs2zk7c3r828gds8ajbnr": "Chicken Risotto.webp",
  "kh71m5zgcvjwhqy3k4c3w7dxd18akthw": "Oxygen Chips Salted Vinegar.webp",
  "kh71yrwq0b7f6hqy11vds3s1dn8ajym3": "Grilled Steak 100g.webp",
  "kh723vqhzddn883a24e6jm8e5n8ajeae": "Zuchini Pasta.webp",
  "kh7288t8fxjr4rqm1f0t95q3px8akkqf": "Ummali.webp",
  "kh72kw3vp1sczv2h44msmje2th8ajt5v": "Mashed Potato 100g.webp",
  "kh72qahv2wy957tgb0nkm13yth8akpk7": "Immune Shot.webp",
  "kh72v6zznddwvkzhqd3x6pdjrh8ass16": "kh72v6zznddwvkzhqd3x6pdjrh8ass16.webp",
  "kh730v82kevmwhqq1seznh0ar98ajn1z": "Heaven Ball.webp",
  "kh731zc16eg2q9127p8sysa83n8ak373": "Rice 100g.webp",
  "kh73e1bnm6gq4hrwc5wv344hkx8akxjz": "French Toast.webp",
  "kh73jj9t3tt6z7cbx66tw0pbmn8ak7me": "Cordon Bleu.webp",
  "kh73ksjs4c66tttbxp17vf2ax18ak1wy": "Talbina Majdoul.webp",
  "kh73skpdq288ht3zebe0k7hadn8ajzdx": "kh73skpdq288ht3zebe0k7hadn8ajzdx.webp",
  "kh73wna15k91wxs9pk0r9ztaf18ajbeq": "Power Ball.webp",
  "kh73wwtxsmvx0waz8w4mxmq7wd8akkvt": "Matcha Glow Juice.webp",
  "kh73ybvz6cn1e4274zddsjnncs8ajq8b": "Mashed Potato 100g.webp",
  "kh73yd5d4hrp0emecp6krsvjks8ajsbk": "Energy Balls 3pcs.webp",
  "kh74a5x3gsgpdctybh9cwgf1jh8ajwm1": "Adrenaline Snickers.webp",
  "kh74asz4qt3n101cyrfpfj6cyd8akdrt": "Oxygen Chips Chipotle Chili.webp",
  "kh74gvqtr5qzzmhnvebfw9rvfs8asyx6": "Pomegranate.webp",
  "kh74rxcp2fxz8hp1vtc4b4ydx18ajhkv": "Gathering Box Sub Sandwiches.webp",
  "kh750g7kc9gdh3ffvevxqnk5ns8akmqb": "Rice 100g.webp",
  "kh751ybzw49wwnqkdvzhb4pc2x8akba0": "Mashed Potato 100g.webp",
  "kh7563dqf8c821re1wryzdzyqn8akgsg": "Crispy Chicken Burger.webp",
  "kh758y7pyf95nws582mmvcha6h8ar99h": "Detox Shot.webp",
  "kh75fhd2ec853ezmwt64061c5d8amhk8": "Vanilla Muffin.webp",
  "kh75k7j22bc189dhq1ga6n2pmd8aky45": "Pepperoni Pizza.webp",
  "kh75qvdhspqhpfgy7dgnfg0dx58ajy18": "Tarte.webp",
  "kh75v5s77te4wqwbec52ee33bs8akb99": "Mix Strawberry & Blueberry.webp",
  "kh760yz7ep50xtrk06aqb1pymn8akh00": "Fresh Orange Juice.webp",
  "kh765b4e7sv12dxqja97t65yas8akztk": "Mashed Potato 100g.webp",
  "kh76f15b4fe9n2h7j0rwgy62318an7wx": "kh76f15b4fe9n2h7j0rwgy62318an7wx.webp",
  "kh76n0hgy2qyy2bkbzjpaw97m58aktx8": "Pistachio Lava Cake.webp",
  "kh772ysy22txbp7gcpk9abr92d8ajpq3": "Beef Fajita Sandwich.webp",
  "kh774cmt10krzaywsdz8xbc6cd8akmvm": "Grilled Steak 100g.webp",
  "kh77age5f6dfkcaa6a9t29szkd8akk6k": "Classic Fattoush Salad.webp",
  "kh77bfaaxk4yej8f7725pqn2318akgw0": "Grilled Chicken 100g.webp",
  "kh77ha1ft29qj661bbvns7yem18ak8d5": "Alka Live Water 500ml.webp",
  "kh77j0mwcx6e54q67tp48h7a1s8ajwaj": "Oxygen Chips Sweet Chili Pepper.webp",
  "kh77nmgyzwdk6n1nh41h75atys8ak9wg": "Sweet Potato Energy Booster.webp",
  "kh77wf2vmm2ex23q31rgy1m5sn8ajzq1": "Mashed Sweet Potato 100g.webp",
  "kh7842g76acza1d7ej2q4mbj798ajjpf": "Adrenaline Beef Burger.webp",
  "kh786j77xqw9bqn5rxfnddez9n8anw64": "Beef Fajita Sandwich.webp",
  "kh786xdpqfxzwr62r2tm7n8b458aj83a": "Gathering Box Sandwiches.webp",
  "kh78daf37cmvfnajq17gj4na098aj1a3": "Beef Kofta Saffron Rice.webp",
  "kh78eqwajt6g3hek0whwss7j9d8aj9kg": "Pizza Slice Veggie.webp",
  "kh78mnr9dxs1jnbhy3k8p19rrd8akvjd": "Oxygen Chips Hot Honey BBQ.webp",
  "kh78t0zx6mght5t3xysf2pb4ed8akzx1": "Fresh Pineapple Cut.webp",
  "kh795s6v6d5x2y8j4wtqcach6d8bdpkx": "Alka Live Water 500ml.webp",
  "kh797hyphk144h5c55h4v6xywh8aka19": "Vanilla Muffin.webp",
  "kh799564nn9ync0k42qw4f9vah8akpe7": "Fresh Mandarin with Pomegranate.webp",
  "kh79argn6md0erqn6mzffc0yax8amb2w": "kh79argn6md0erqn6mzffc0yax8amb2w.webp",
  "kh79br6m62vqhfb7a97nhdv6z18akfc0": "Tuna Sandwich.webp",
  "kh79egjx0ty2ggd4sqjx2r4cqd8aj4p9": "Chicken Alfredo دجاج ألفريدو.webp",
  "kh79ncnrxpr34g98a59mv4hh658am1dv": "Beef Shawarma with Beetroot Rice.webp",
  "kh79r29kptxqw0z815j0qg24rn8aspct": "Chicken Avocado Sandwich.webp",
  "kh79rpm0xw20wxsz2y7p85zb5n8ajjey": "Matcha Cheesecake.webp",
  "kh79rzm766474pbx2asv1e2qj18ak6ee": "Veggie Pizza.webp",
  "kh79zem7fn7y9fnahmnrpfngph8akg6f": "Pecan with Chocolate.webp",
  "kh7a1zcvscm10amwj0f5z65sbh8as89t": "Basbousa Coconut.webp",
  "kh7a4cnx1s6rpdsn6kq922ybs98aj6ba": "Gathering Box Burgers.webp",
  "kh7a4rk0z5bqrzt06jqd9br2k58akmk8": "Vitargo Drink-orange Flavour.webp",
  "kh7a6d8q3p6c0pzbqybm649vy98arpyv": "Chicken Fajita Sandwich.webp",
  "kh7a6nq7b7nmcdwhc961nkeqvd8ajq63": "Gathering Box Tacos.webp",
  "kh7a8qa19ftrkjkz4b7d7gmbwx8ajbm8": "Vitargo Drink-mango Flavour.webp",
  "kh7acqz5me2wzcpknt0zvs9ev58ars2h": "Matcha Cheesecake.webp",
  "kh7ax8zh24yrdst7a8z96m0y3x8akns3": "Halloumi Pesto Sandwich.webp",
  "kh7b0815m2eab85cdxxmprr71d8akbzb": "Rice 100g.webp",
  "kh7b7313h06wc1h5knpy6d3jjh8akwg9": "Zaatar Omlette.webp",
  "kh7b9ds58yev5f4gg8x5etm8vd8ajdf6": "Pizza Slice Pepperoni.webp",
  "kh7bahn65zged1pfcqm5dtx4fx8ajztx": "Rice 100g.webp",
  "kh7bpqhweqdadbjqy2mxfrzm5x8aka04": "Kunafa Pistachio Balls.webp",
  "kh7bsag9arrfn6p7qaptpmcn998ajxap": "Beef Shawarma.webp",
  "kh7bt118pwb3k27bc6v2skswx58ajz64": "Protein Lava Cake.webp",
  "kh7c5fg8x3pem8dsf51kc5g9598ajfp3": "Grilled Steak 100g.webp",
  "kh7c5rzx2r9drvcevnknwkne2n8arep9": "Basbousa Pistachio.webp",
  "kh7ca97qf0hjm8whcstzqb9nr98akdgy": "Grilled Steak 100g.webp",
  "kh7cm9nqtm9j878pb38p0yg40x8aknxj": "Grilled Chicken 100g.webp",
  "kh7cyzde53cdvw16bgfyqp0fkn8asf8w": "PROTEIN LAZY CAKE.webp",
  "kh7d0femqg3e1v5pttgzd09khh8akdbw": "Hazelnut Lava Cake.webp",
  "kh7d0mrwvwxds4gwm755t9xwqs8ajbnc": "Mashed Sweet Potato 100g.webp",
  "kh7d1rge4jbzdaj8xyt2qcsqcs8arsrd": "kh7d1rge4jbzdaj8xyt2qcsqcs8arsrd.webp",
  "kh7daxztdpjaz04ngm5symb6v58akfa6": "Pecan Caramel Cheesecake.webp",
  "kh7dk7745gqef0qqrc85h5y65d8akaek": "Pomegranate.webp",
  "kh7dq6wa96x7xep5vfm6kzr5hs8ak897": "Shishtawook Sandwich.webp",
  "kh7e0aev3p6emy56syyjpy6xw58art44": "Chicken Shawarma.webp",
  "kh7ec7fv8y10yp0kxdsfgaeahn8akych": "Mashed Sweet Potato 100g.webp",
  "kh7ehd8tdqav5r6wem29kvyn5h8ajk3t": "Basbousa Pistachio.webp",
  "kh7ekj6828tebjd0gwfjkrjdzh8asvfe": "French Toast.webp",
  "kh7em0mzary9pygagj0c6kc4rh8ajyz3": "Grilled Chicken 100g.webp",
  "kh7er9qabdbryjn0ep4kmkc63x8ajd2a": "Grilled Chicken 100g.webp",
  "kh7ervfsnpb1qyy0asnsjmfr6s8arag5": "kh7ervfsnpb1qyy0asnsjmfr6s8arag5.webp",
  "kh7f252e030bx917fv98dycvss8asek8": "Protein Lava Cake.webp",
  "kh7f4amqpewtdz18ksrv46adgs8arz75": "kh7f4amqpewtdz18ksrv46adgs8arz75.webp",
  "kh7f54dgftjc6462m0d6rteba58ajy01": "Detox Shot.webp",
  "kh7fa60ep4sjp1z6jsfrnfpjy98akyyt": "Basbousa Coconut.webp",
  "kh7fh2jrg1hwfdvvtevccp99998akd3m": "Mashed Sweet Potato 100g.webp",
  "kh7fj7z90acaetbkhrdt0e41s18akjvv": "Vegan Avocado Toast.webp",
  "kh7fmh3vkqy9d1ev60gp4q2d9d8akmks": "Shakshouka.webp",
  "kh7fqzq5w59e8cp2pdhtvb0h218arqwc": "kh7fqzq5w59e8cp2pdhtvb0h218arqwc.webp",
  "kh7fw9kymhehv00n6pf1f3w82h8ajke4": "Mix Pomegranate&pineapple.webp",
  "kh7fyfpkb4dsqat96pme8rbdks8aj8t7": "Healthy Chicken Majboos.webp",
};

export function getPosMealImageById(id?: string | null) {
  const filename = id ? POS_MEAL_IMAGES_BY_ID[id] : undefined;
  return filename ? `/pos-meals/thumbs/${encodeURIComponent(filename)}` : null;
}

function normalizeMealName(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .toUpperCase();
}

export function getPosMealImage(...names: Array<string | null | undefined>) {
  for (const name of names) {
    if (!name) continue;
    const filename = POS_MEAL_IMAGES[normalizeMealName(name)];
    if (filename) {
      const thumbnail = filename.replace(/\.[^.]+$/, ".webp");
      return `/pos-meals/thumbs/${encodeURIComponent(thumbnail)}`;
    }
  }
  return null;
}
