import React, {useState} from 'react';
import {FlatList,View,ScrollView,TextInput,useWindowDimensions} from 'react-native';
import {Image} from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import {useQuery} from 'convex/react';
import {api} from '@/api';
import {useRouter} from 'expo-router';
import {T,Btn,Chip} from '@/components/ui';
import {useContentLanguage} from '@/useContentLanguage';
import {fonts} from '@/theme';
type Dish={id:string;ingredients:string[];ar:string;en:string;category:string;channels:string[];image:string|null;calories:number|null;protein:number|null;carbs:number|null;fats:number|null};
const none:Dish[]=[];
export default function RestaurantMenu(){
 // قراءة حية من الخادم: الصور والأسماء والسعرات تتحدّث من لوحة التحكم بلا بناء جديد للتطبيق.
 const live=useQuery(api.restaurantCatalog.list,{}) as Dish[]|undefined;const catalog=live??none;const [broken,setBroken]=useState<Record<string,boolean>>({});
 const {language}=useContentLanguage();const ar=language==='ar';const router=useRouter();const [channel,setChannel]=useState('all');const [q,setQ]=useState('');const [cat,setCat]=useState('all');const width=Math.min(useWindowDimensions().width,1100);const cols=width<350?1:width>800?4:2;
 const menus=[['all','المنيو كامل','Full menu'],['online','أونلاين','Online'],['subscription','وجبات باقات الاشتراك','Subscription dishes'],['outlet','المنافذ','Outlets']];
 const cats=[['all','الكل','All'],['breakfast','الفطور','Breakfast'],['sandwiches','ساندويتشات','Sandwiches'],['chicken','الدجاج','Chicken'],['beef','اللحوم','Beef'],['seafood','الأسماك والروبيان','Seafood'],['pasta','الباستا','Pasta'],['salads','السلطات والشوربات','Salads'],['snacks','الحلويات والسناك','Snacks'],['drinks','المشروبات','Drinks'],['boxes','البوكسات','Boxes'],['other','أطباق متنوعة','More dishes']];
 const meals=catalog.filter(m=>(channel==='all'||m.channels.includes(channel))&&(cat==='all'||m.category===cat)&&`${m.ar} ${m.en}`.toLowerCase().includes(q.trim().toLowerCase()));
 return <FlatList key={cols} data={meals} numColumns={cols} keyExtractor={m=>m.id} style={{flex:1,backgroundColor:'#edf5f8'}} contentContainerStyle={{padding:12,paddingBottom:36,maxWidth:1100,width:'100%',alignSelf:'center'}} columnWrapperStyle={cols>1?{gap:10}:undefined} keyboardShouldPersistTaps="handled" ListHeaderComponent={<View style={{gap:16,marginBottom:16}}><View style={{backgroundColor:'#183343',borderRadius:16,padding:24,gap:12}}><T w="black" style={{fontSize:30,color:'#fff'}}>{ar?'منيو المطعم':'Restaurant menu'}</T><T style={{color:'#bce7f7',lineHeight:26}}>{ar?'كل اللي تحبه، في منيو واحد.':'Your favourites. One menu.'}</T><T style={{color:'#fff',lineHeight:24}}>{ar?'تصفح الأطباق والمكونات. اختيار وجبات اشتراكك متاح من حسابي.':'Explore dishes and ingredients. Choose subscription meals from Account.'}</T></View><Btn label={ar?'اختيار وجبات اشتراكي':'Choose my subscription meals'} variant="outline" onPress={()=>router.push('/menu')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{menus.map(([id,a,e])=><Chip key={id} label={ar?a:e} active={channel===id} onPress={()=>{setChannel(id);setCat('all');setQ('');}}/>)}</ScrollView>{channel==='subscription'&&<T>{ar?'للاطلاع على الوجبات المتاحة ضمن الباقات':'Browse dishes included in subscription plans'}</T>}<TextInput value={q} onChangeText={setQ} accessibilityLabel={ar?'ابحث عن وجبة':'Search dishes'} placeholder={ar?'ابحث عن وجبتك المفضلة':'Find your favourite dish'} placeholderTextColor="#526b7a" style={{backgroundColor:'#fff',borderWidth:1,borderColor:'#a5beca',borderRadius:12,padding:14,fontFamily:fonts.regular,color:'#183343',minHeight:48,textAlign:ar?'right':'left'}}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{cats.map(([id,a,e])=><Chip key={id} label={ar?a:e} active={cat===id} onPress={()=>setCat(id)}/>)}</ScrollView><T>{meals.length} {ar?'صنف':'dishes'}</T></View>}
 renderItem={({item:m})=><View style={{width:(width-24-10*(cols-1))/cols,backgroundColor:'#183343',borderRadius:14,overflow:'hidden',marginBottom:12}}>{m.image&&!broken[m.id]?<Image source={{uri:m.image}} recyclingKey={m.id} cachePolicy="disk" transition={150} accessibilityLabel={ar?(m.ar||m.en):m.en} style={{width:'100%',aspectRatio:1}} contentFit="cover" onError={()=>setBroken(o=>({...o,[m.id]:true}))}/>:<View style={{aspectRatio:1,backgroundColor:'#e0edf3',alignItems:'center',justifyContent:'center'}}><Ionicons name="restaurant-outline" size={40} color="#7b97a6" accessibilityLabel={ar?(m.ar||m.en):m.en}/></View>}<View style={{padding:12,gap:8}}><T literal w="bold" style={{color:'#fff',fontSize:14}}>{ar?(m.ar||m.en):m.en}</T>{ar&&m.ar&&<T literal style={{color:'#c5dae5',fontSize:11}}>{m.en}</T>}{m.ingredients.length>0&&<T literal style={{color:'#c5dae5',fontSize:11,lineHeight:19}}>{(ar?'المكونات: ':'Ingredients: ')+m.ingredients.join(ar?'، ':', ')}</T>}<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(['calories','protein','carbs','fats'] as const).map((key,i)=><View key={key}><T style={{fontSize:9,color:'#c5dae5'}}>{(ar?['سعرة','بروتين','كارب','دهون']:['kcal','Protein','Carbs','Fat'])[i]}</T><T w="bold" style={{color:'#79dcfa',fontSize:13}}>{m[key]??'—'}{m[key]!==null&&i>0?'g':''}</T></View>)}</View></View></View>}
 ListEmptyComponent={live===undefined?<View style={{padding:24}}><T>{ar?'جارٍ تحميل المنيو…':'Loading the menu…'}</T></View>:<View style={{padding:24,gap:12}}><T>{ar?'لا توجد نتائج':'No results'}</T><Btn label={ar?'مسح البحث والتصنيف':'Clear search and category'} onPress={()=>{setQ('');setCat('all');}}/></View>}/>;
}
