import { mutation, internalMutation, query } from "./_generated/server";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";

// ==================================================================
// المالية — المرحلة 2: محرك الترحيل (Posting Engine) + الترحيل التلقائي
//   قلب النظام: كل قيد متوازن (مدين = دائن)، برقم متسلسل، وفترة صحيحة.
//   الترحيل التلقائي لا يكسر أي عملية أبدًا (يُغلَّف بحماية).
// ==================================================================

type Ctx = any;

// ---------- أدوات مشتركة ----------

// إيجاد/إنشاء الفترة المالية الشهرية لتاريخ معيّن (yyyy-MM-dd).
async function ensurePeriod(ctx: Ctx, dateISO: string): Promise<Id<"finPeriods">> {
  const ym = dateISO.slice(0, 7);            // yyyy-MM
  const year = Number(dateISO.slice(0, 4));
  const all = await ctx.db.query("finPeriods").collect();
  const found = all.find((p: any) => p.name === ym);
  if (found) return found._id;
  const mm = dateISO.slice(5, 7);
  const lastDay = new Date(year, Number(mm), 0).getDate();
  return await ctx.db.insert("finPeriods", {
    name: ym,
    fiscalYear: year,
    startDate: `${ym}-01`,
    endDate: `${ym}-${String(lastDay).padStart(2, "0")}`,
    status: "open",
    createdAt: Date.now(),
  });
}

// هل الفترة تسمح بالترحيل؟
async function assertPeriodOpen(ctx: Ctx, periodId: Id<"finPeriods">) {
  const p = await ctx.db.get(periodId);
  if (p && p.status !== "open") {
    throw new Error(`الفترة ${p.name} مقفولة — لا يمكن الترحيل عليها`);
  }
}

// الرقم المتسلسل التالي للقيد.
async function nextJournalNumber(ctx: Ctx): Promise<string> {
  let c = await ctx.db.query("finCounters").withIndex("by_key", (q: any) => q.eq("key", "journal")).first();
  if (!c) {
    const id = await ctx.db.insert("finCounters", { key: "journal", prefix: "JV-", value: 1 });
    c = await ctx.db.get(id);
    return `JV-${String(1).padStart(6, "0")}`;
  }
  const next = (c.value || 0) + 1;
  await ctx.db.patch(c._id, { value: next });
  return `${c.prefix || "JV-"}${String(next).padStart(6, "0")}`;
}

// حساب بالكود (كاش) — للترحيل التلقائي.
async function accByCode(ctx: Ctx, code: string): Promise<Id<"finAccounts"> | null> {
  const a = await ctx.db.query("finAccounts").withIndex("by_code", (q: any) => q.eq("code", code)).first();
  return a?._id ?? null;
}

type LineIn = {
  accountId: Id<"finAccounts">;
  debit?: number;
  credit?: number;
  description?: string;
  costCenterId?: Id<"finCostCenters">;
  partyType?: string;
  partyId?: string;
  documentRef?: string;
};

// إنشاء قيد كامل (رأس + أسطر) بعد التحقق من التوازن. الدالة الأساسية لكل ترحيل.
export async function postEntry(
  ctx: Ctx,
  opts: {
    entryDate: string;
    description: string;
    lines: LineIn[];
    journalType: string;
    branchId?: Id<"posBranches">;
    costCenterId?: Id<"finCostCenters">;
    sourceType?: string;
    sourceId?: string;
    isAutoGenerated?: boolean;
    status?: "draft" | "posted";
    createdBy?: Id<"users">;
    notes?: string;
  },
): Promise<{ entryId: Id<"finJournalEntries">; entryNumber: string }> {
  const lines = (opts.lines || []).filter((l) => (l.debit || 0) !== 0 || (l.credit || 0) !== 0);
  if (lines.length < 2) throw new Error("القيد يحتاج سطرين على الأقل");
  const round = (n: number) => Math.round((n || 0) * 1000) / 1000;
  const totalDebit = round(lines.reduce((s, l) => s + (l.debit || 0), 0));
  const totalCredit = round(lines.reduce((s, l) => s + (l.credit || 0), 0));
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(`القيد غير متوازن: مدين ${totalDebit} ≠ دائن ${totalCredit}`);
  }
  if (totalDebit === 0) throw new Error("القيد بقيمة صفر");

  const periodId = await ensurePeriod(ctx, opts.entryDate);
  await assertPeriodOpen(ctx, periodId);
  const entryNumber = await nextJournalNumber(ctx);
  const now = Date.now();
  const status = opts.status || "posted";

  const entryId = await ctx.db.insert("finJournalEntries", {
    entryNumber,
    journalType: opts.journalType as any,
    entryDate: opts.entryDate,
    periodId,
    costCenterId: opts.costCenterId,
    branchId: opts.branchId,
    description: opts.description,
    totalDebit,
    totalCredit,
    postingStatus: status,
    isAutoGenerated: !!opts.isAutoGenerated,
    sourceType: opts.sourceType,
    sourceId: opts.sourceId,
    postedBy: status === "posted" ? opts.createdBy : undefined,
    postedAt: status === "posted" ? now : undefined,
    createdBy: opts.createdBy,
    notes: opts.notes,
    createdAt: now,
  });

  let i = 1;
  for (const l of lines) {
    await ctx.db.insert("finJournalLines", {
      entryId,
      lineNumber: i++,
      accountId: l.accountId,
      description: l.description,
      costCenterId: l.costCenterId ?? opts.costCenterId,
      debit: round(l.debit || 0),
      credit: round(l.credit || 0),
      partyType: l.partyType,
      partyId: l.partyId,
      documentRef: l.documentRef,
      createdAt: now,
    });
  }
  return { entryId, entryNumber };
}

// ---------- الترحيل التلقائي: فاتورة POS مدفوعة ----------
// يُستدعى بأمان بعد الدفع. idempotent عبر (sourceType, sourceId).
// أي خطأ لا يكسر البيع — يُبتلع ويُسجَّل.
export async function autoPostPosTicket(ctx: Ctx, ticketId: Id<"posTickets">): Promise<boolean> {
  try {
    const t: any = await ctx.db.get(ticketId);
    if (!t || t.status !== "PAID") return false;
    if (t.isNonRevenue) return false; // خارج الإيراد لا يُرحَّل كمبيعات

    // منع التكرار
    const existing = await ctx.db
      .query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "posTicket").eq("sourceId", String(ticketId)))
      .first();
    if (existing) return false;

    const date = new Date(t.paidAt || t.createdAt || Date.now()).toISOString().slice(0, 10);
    const total = Number(t.total || 0);
    if (total <= 0) return false;

    // الحسابات
    const salesAcc = await accByCode(ctx, "4110");        // مبيعات المطعم
    const vatAcc = await accByCode(ctx, "2130");          // ض.ق.م مستحقة
    const cashAcc = await accByCode(ctx, "1111");         // درج الكاشير
    const cardAcc = await accByCode(ctx, "1130");         // بطاقات تحت التحصيل
    const platformAcc = await accByCode(ctx, "1140");     // منصّات تحت التحصيل
    const discountAcc = await accByCode(ctx, "4195");     // خصومات ممنوحة
    if (!salesAcc || !cashAcc) return false;

    const tax = Number(t.tax || 0);
    const discount = Number(t.discount || 0);
    const netRevenue = total - tax; // الإيراد صافي الضريبة

    // توزيع المدفوعات على الحسابات (كاش/كارت/منصّة)
    const payments: Array<{ method: string; amount: number }> = Array.isArray(t.payments) && t.payments.length
      ? t.payments
      : [{ method: String(t.paymentMethod || "cash"), amount: total }];

    const methodAcc = (m: string): Id<"finAccounts"> => {
      const s = String(m || "").toLowerCase();
      if (s.includes("card") || s.includes("visa") || s.includes("shabaka") || s.includes("شبكة")) return cardAcc || cashAcc!;
      if (["talabat", "snoonu", "rafeeq", "keeta", "deliveroo"].some((p) => s.includes(p))) return platformAcc || cardAcc || cashAcc!;
      return cashAcc!; // cash / transfer / staff → صندوق
    };

    const lines: LineIn[] = [];
    // مدين: طرق الدفع
    for (const p of payments) {
      const amt = Number(p.amount || 0);
      if (amt <= 0) continue;
      lines.push({ accountId: methodAcc(p.method), debit: amt, description: `تحصيل ${p.method}` });
    }
    // مدين: الخصم الممنوح (إن وُجد)
    if (discount > 0 && discountAcc) {
      lines.push({ accountId: discountAcc, debit: discount, description: "خصم ممنوح" });
    }
    // دائن: المبيعات (صافي الضريبة، ومضاف إليه الخصم لأن الإيراد الإجمالي قبل الخصم)
    lines.push({ accountId: salesAcc, credit: netRevenue + discount, description: `فاتورة #${t.ticketNumber}` });
    // دائن: الضريبة
    if (tax > 0 && vatAcc) lines.push({ accountId: vatAcc, credit: tax, description: "ض.ق.م" });

    await postEntry(ctx, {
      entryDate: date,
      description: `مبيعات POS — فاتورة #${t.ticketNumber}`,
      lines,
      journalType: "auto_sales",
      branchId: t.branchId,
      sourceType: "posTicket",
      sourceId: String(ticketId),
      isAutoGenerated: true,
      createdBy: t.cashierId,
    });
    return true;
  } catch (e) {
    console.error("autoPostPosTicket failed (non-blocking):", String(e));
    return false;
  }
}

// ترحيل دفعي لكل الفواتير المدفوعة غير المرحّلة (آمن، يُعاد تشغيله).
export const backfillPosTickets = mutation({
  args: { limit: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const paid = await ctx.db.query("posTickets").withIndex("by_status", (q) => q.eq("status", "PAID")).collect();
    let posted = 0, skipped = 0;
    const lim = args.limit ?? 100000;
    for (const t of paid) {
      if (posted >= lim) break;
      const ok = await autoPostPosTicket(ctx, t._id);
      ok ? posted++ : skipped++;
    }
    return { paidTickets: paid.length, posted, skipped };
  },
});

// ---------- قيد يدوي عام (للمحاسب) ----------
export const createManualEntry = mutation({
  args: {
    entryDate: v.string(),
    description: v.string(),
    journalType: v.optional(v.string()),
    branchId: v.optional(v.id("posBranches")),
    costCenterId: v.optional(v.id("finCostCenters")),
    notes: v.optional(v.string()),
    status: v.optional(v.union(v.literal("draft"), v.literal("posted"))),
    lines: v.array(v.object({
      accountId: v.id("finAccounts"),
      debit: v.optional(v.number()),
      credit: v.optional(v.number()),
      description: v.optional(v.string()),
      costCenterId: v.optional(v.id("finCostCenters")),
      partyType: v.optional(v.string()),
      partyId: v.optional(v.string()),
    })),
  },
  handler: async (ctx, args) => {
    return await postEntry(ctx, {
      entryDate: args.entryDate,
      description: args.description,
      lines: args.lines as any,
      journalType: args.journalType || "general",
      branchId: args.branchId,
      costCenterId: args.costCenterId,
      status: args.status || "posted",
      notes: args.notes,
      isAutoGenerated: false,
    });
  },
});

// ---------- تسجيل مصروف سريع (مبسّط للمحاسب) ----------
// مدين: حساب المصروف | دائن: كاش/بنك
export const recordExpense = mutation({
  args: {
    entryDate: v.string(),
    expenseAccountId: v.id("finAccounts"),
    paidFromAccountId: v.id("finAccounts"),
    amount: v.number(),
    description: v.string(),
    costCenterId: v.optional(v.id("finCostCenters")),
    branchId: v.optional(v.id("posBranches")),
  },
  handler: async (ctx, args) => {
    if (args.amount <= 0) throw new Error("المبلغ يجب أن يكون أكبر من صفر");
    return await postEntry(ctx, {
      entryDate: args.entryDate,
      description: args.description,
      journalType: "general",
      branchId: args.branchId,
      costCenterId: args.costCenterId,
      isAutoGenerated: false,
      lines: [
        { accountId: args.expenseAccountId, debit: args.amount, description: args.description },
        { accountId: args.paidFromAccountId, credit: args.amount, description: "سداد" },
      ],
    });
  },
});

// ---------- عكس قيد مُرحَّل (بدل الحذف — للحفاظ على سجل التدقيق) ----------
export const reverseEntry = mutation({
  args: { entryId: v.id("finJournalEntries"), reason: v.string() },
  handler: async (ctx, args) => {
    const entry: any = await ctx.db.get(args.entryId);
    if (!entry) throw new Error("القيد غير موجود");
    if (entry.postingStatus !== "posted") throw new Error("لا يمكن عكس قيد غير مُرحَّل");
    if (entry.reversalEntryId) throw new Error("القيد معكوس بالفعل");
    const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q) => q.eq("entryId", args.entryId)).collect();
    const today = new Date().toISOString().slice(0, 10);
    const rev = await postEntry(ctx, {
      entryDate: today,
      description: `عكس: ${entry.description} — ${args.reason}`,
      journalType: "reversing",
      branchId: entry.branchId,
      costCenterId: entry.costCenterId,
      isAutoGenerated: false,
      lines: lines.map((l: any) => ({
        accountId: l.accountId,
        debit: l.credit,   // معكوس
        credit: l.debit,
        description: `عكس ${l.description || ""}`,
        costCenterId: l.costCenterId,
        partyType: l.partyType,
        partyId: l.partyId,
      })),
    });
    await ctx.db.patch(entry._id, { postingStatus: "reversed", reversalEntryId: rev.entryId });
    await ctx.db.patch(rev.entryId, { reversedEntryId: entry._id });
    return rev;
  },
});

// ---------- استعلام: القيود (مع فلاتر) ----------
export const listJournalEntries = query({
  args: { limit: v.optional(v.number()), fromDate: v.optional(v.string()), toDate: v.optional(v.string()) },
  handler: async (ctx, args) => {
    let entries = await ctx.db.query("finJournalEntries").withIndex("by_date").order("desc").collect();
    if (args.fromDate) entries = entries.filter((e) => e.entryDate >= args.fromDate!);
    if (args.toDate) entries = entries.filter((e) => e.entryDate <= args.toDate!);
    entries = entries.slice(0, args.limit ?? 200);
    // إرفاق الأسطر
    const out = [];
    for (const e of entries) {
      const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q) => q.eq("entryId", e._id)).collect();
      out.push({ ...e, lines });
    }
    return out;
  },
});
