import { mutation, internalMutation, query } from "./_generated/server";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";
import { requireRoleOrPermission } from "./sessions";

const FINANCE_ROLES = ["ACCOUNTANT", "FINANCE_MANAGER"];
const FINANCE_PERMISSIONS = ["/finance"];

async function requireFinance(ctx: Ctx, token?: string) {
  return await requireRoleOrPermission(ctx, token, {
    roles: FINANCE_ROLES,
    permissions: FINANCE_PERMISSIONS,
  });
}

async function auditFinance(ctx: Ctx, actor: any, action: string, entityId?: string, details?: any) {
  const user: any = actor?.userId ? await ctx.db.get(actor.userId as any) : null;
  await ctx.db.insert("auditLog", {
    actorUserId: actor?.userId as any,
    actorName: user?.name,
    actorRole: actor?.role,
    action,
    entityType: "finance",
    entityId,
    details: details ? JSON.stringify(details) : undefined,
    createdAt: Date.now(),
  });
}

// ==================================================================
// المالية — المرحلة 2: محرك الترحيل (Posting Engine) + الترحيل التلقائي
//   قلب النظام: كل قيد متوازن (مدين = دائن)، برقم متسلسل، وفترة صحيحة.
//   الترحيل التلقائي لا يكسر أي عملية أبدًا (يُغلَّف بحماية).
// ==================================================================

type Ctx = any;

// ---------- أدوات مشتركة ----------

// إيجاد/إنشاء الفترة المالية الشهرية لتاريخ معيّن (yyyy-MM-dd).
async function ensurePeriod(ctx: Ctx, dateISO: string): Promise<Id<"finPeriods">> {
  const ym = dateISO.slice(0, 7);            // yyyy-MM
  const year = Number(dateISO.slice(0, 4));
  const all = await ctx.db.query("finPeriods").collect();
  const found = all.find((p: any) => p.name === ym);
  if (found) return found._id;
  const mm = dateISO.slice(5, 7);
  const lastDay = new Date(year, Number(mm), 0).getDate();
  return await ctx.db.insert("finPeriods", {
    name: ym,
    fiscalYear: year,
    startDate: `${ym}-01`,
    endDate: `${ym}-${String(lastDay).padStart(2, "0")}`,
    status: "open",
    createdAt: Date.now(),
  });
}

// هل الفترة تسمح بالترحيل؟
async function assertPeriodOpen(ctx: Ctx, periodId: Id<"finPeriods">) {
  const p = await ctx.db.get(periodId);
  if (p && p.status !== "open") {
    throw new Error(`الفترة ${p.name} مقفولة — لا يمكن الترحيل عليها`);
  }
}

// الرقم المتسلسل التالي للقيد.
async function nextJournalNumber(ctx: Ctx): Promise<string> {
  let c = await ctx.db.query("finCounters").withIndex("by_key", (q: any) => q.eq("key", "journal")).first();
  if (!c) {
    const id = await ctx.db.insert("finCounters", { key: "journal", prefix: "JV-", value: 1 });
    c = await ctx.db.get(id);
    return `JV-${String(1).padStart(6, "0")}`;
  }
  const next = (c.value || 0) + 1;
  await ctx.db.patch(c._id, { value: next });
  return `${c.prefix || "JV-"}${String(next).padStart(6, "0")}`;
}

// حساب بالكود (كاش) — للترحيل التلقائي.
async function accByCode(ctx: Ctx, code: string): Promise<Id<"finAccounts"> | null> {
  const a = await ctx.db.query("finAccounts").withIndex("by_code", (q: any) => q.eq("code", code)).first();
  return a?._id ?? null;
}

type LineIn = {
  accountId: Id<"finAccounts">;
  debit?: number;
  credit?: number;
  description?: string;
  costCenterId?: Id<"finCostCenters">;
  partyType?: string;
  partyId?: string;
  documentRef?: string;
};

// إنشاء قيد كامل (رأس + أسطر) بعد التحقق من التوازن. الدالة الأساسية لكل ترحيل.
export async function postEntry(
  ctx: Ctx,
  opts: {
    entryDate: string;
    description: string;
    lines: LineIn[];
    journalType: string;
    branchId?: Id<"posBranches">;
    costCenterId?: Id<"finCostCenters">;
    sourceType?: string;
    sourceId?: string;
    isAutoGenerated?: boolean;
    status?: "draft" | "posted";
    createdBy?: Id<"users">;
    notes?: string;
  },
): Promise<{ entryId: Id<"finJournalEntries">; entryNumber: string }> {
  const lines = (opts.lines || []).filter((l) => (l.debit || 0) !== 0 || (l.credit || 0) !== 0);
  if (lines.length < 2) throw new Error("القيد يحتاج سطرين على الأقل");
  const round = (n: number) => Math.round((n || 0) * 1000) / 1000;
  const totalDebit = round(lines.reduce((s, l) => s + (l.debit || 0), 0));
  const totalCredit = round(lines.reduce((s, l) => s + (l.credit || 0), 0));
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(`القيد غير متوازن: مدين ${totalDebit} ≠ دائن ${totalCredit}`);
  }
  if (totalDebit === 0) throw new Error("القيد بقيمة صفر");

  const periodId = await ensurePeriod(ctx, opts.entryDate);
  await assertPeriodOpen(ctx, periodId);
  const entryNumber = await nextJournalNumber(ctx);
  const now = Date.now();
  const status = opts.status || "posted";

  const entryId = await ctx.db.insert("finJournalEntries", {
    entryNumber,
    journalType: opts.journalType as any,
    entryDate: opts.entryDate,
    periodId,
    costCenterId: opts.costCenterId,
    branchId: opts.branchId,
    description: opts.description,
    totalDebit,
    totalCredit,
    postingStatus: status,
    isAutoGenerated: !!opts.isAutoGenerated,
    sourceType: opts.sourceType,
    sourceId: opts.sourceId,
    postedBy: status === "posted" ? opts.createdBy : undefined,
    postedAt: status === "posted" ? now : undefined,
    createdBy: opts.createdBy,
    notes: opts.notes,
    createdAt: now,
  });

  let i = 1;
  for (const l of lines) {
    await ctx.db.insert("finJournalLines", {
      entryId,
      lineNumber: i++,
      accountId: l.accountId,
      description: l.description,
      costCenterId: l.costCenterId ?? opts.costCenterId,
      debit: round(l.debit || 0),
      credit: round(l.credit || 0),
      partyType: l.partyType,
      partyId: l.partyId,
      documentRef: l.documentRef,
      createdAt: now,
    });
  }
  return { entryId, entryNumber };
}

// ---------- الترحيل التلقائي: فاتورة POS مدفوعة ----------
// يُستدعى بأمان بعد الدفع. idempotent عبر (sourceType, sourceId).
// أي خطأ لا يكسر البيع — يُبتلع ويُسجَّل.
export async function autoPostPosTicket(ctx: Ctx, ticketId: Id<"posTickets">): Promise<boolean> {
  try {
    const t: any = await ctx.db.get(ticketId);
    if (!t || t.status !== "PAID") return false;
    if (t.isNonRevenue) return false; // خارج الإيراد لا يُرحَّل كمبيعات

    // منع التكرار
    const existing = await ctx.db
      .query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "posTicket").eq("sourceId", String(ticketId)))
      .first();
    if (existing) return false;

    const date = new Date(t.paidAt || t.createdAt || Date.now()).toISOString().slice(0, 10);
    const total = Number(t.total || 0);
    if (total <= 0) return false;

    // الحسابات
    const salesAcc = await accByCode(ctx, "4110");        // مبيعات المطعم
    const vatAcc = await accByCode(ctx, "2130");          // ض.ق.م مستحقة
    const cashAcc = await accByCode(ctx, "1111");         // درج الكاشير
    const cardAcc = await accByCode(ctx, "1130");         // بطاقات تحت التحصيل
    const platformAcc = await accByCode(ctx, "1140");     // منصّات تحت التحصيل
    const discountAcc = await accByCode(ctx, "4195");     // خصومات ممنوحة
    if (!salesAcc || !cashAcc) return false;

    const tax = Number(t.tax || 0);
    const discount = Number(t.discount || 0);
    const netRevenue = total - tax; // الإيراد صافي الضريبة

    // توزيع المدفوعات على الحسابات (كاش/كارت/منصّة)
    const payments: Array<{ method: string; amount: number }> = Array.isArray(t.payments) && t.payments.length
      ? t.payments
      : [{ method: String(t.paymentMethod || "cash"), amount: total }];

    const methodAcc = (m: string): Id<"finAccounts"> => {
      const s = String(m || "").toLowerCase();
      if (s.includes("card") || s.includes("visa") || s.includes("shabaka") || s.includes("شبكة")) return cardAcc || cashAcc!;
      if (["talabat", "snoonu", "rafeeq", "keeta", "deliveroo"].some((p) => s.includes(p))) return platformAcc || cardAcc || cashAcc!;
      return cashAcc!; // cash / transfer / staff → صندوق
    };

    const lines: LineIn[] = [];
    // مدين: طرق الدفع
    for (const p of payments) {
      const amt = Number(p.amount || 0);
      if (amt <= 0) continue;
      lines.push({ accountId: methodAcc(p.method), debit: amt, description: `تحصيل ${p.method}` });
    }
    // مدين: الخصم الممنوح (إن وُجد)
    if (discount > 0 && discountAcc) {
      lines.push({ accountId: discountAcc, debit: discount, description: "خصم ممنوح" });
    }
    // دائن: المبيعات (صافي الضريبة، ومضاف إليه الخصم لأن الإيراد الإجمالي قبل الخصم)
    lines.push({ accountId: salesAcc, credit: netRevenue + discount, description: `فاتورة #${t.ticketNumber}` });
    // دائن: الضريبة
    if (tax > 0 && vatAcc) lines.push({ accountId: vatAcc, credit: tax, description: "ض.ق.م" });

    await postEntry(ctx, {
      entryDate: date,
      description: `مبيعات POS — فاتورة #${t.ticketNumber}`,
      lines,
      journalType: "auto_sales",
      branchId: t.branchId,
      sourceType: "posTicket",
      sourceId: String(ticketId),
      isAutoGenerated: true,
      createdBy: t.cashierId,
    });
    return true;
  } catch (e) {
    console.error("autoPostPosTicket failed (non-blocking):", String(e));
    return false;
  }
}

/** Reverse the accounting effect of a paid POS ticket exactly once. */
export async function autoReversePosTicket(
  ctx: Ctx,
  ticketId: Id<"posTickets">,
  reason: string,
  createdBy?: Id<"users">,
): Promise<boolean> {
  try {
    const original: any = await ctx.db
      .query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "posTicket").eq("sourceId", String(ticketId)))
      .first();
    if (!original || original.postingStatus !== "posted" || original.reversalEntryId) return false;
    const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q: any) => q.eq("entryId", original._id)).collect();
    const rev = await postEntry(ctx, {
      entryDate: new Date().toISOString().slice(0, 10),
      description: `عكس ${original.description} — ${reason}`,
      journalType: "reversing",
      branchId: original.branchId,
      costCenterId: original.costCenterId,
      sourceType: "posTicketReversal",
      sourceId: String(ticketId),
      isAutoGenerated: true,
      createdBy,
      lines: lines.map((l: any) => ({
        accountId: l.accountId,
        debit: l.credit,
        credit: l.debit,
        description: `عكس ${l.description || ""}`,
        costCenterId: l.costCenterId,
        partyType: l.partyType,
        partyId: l.partyId,
        documentRef: l.documentRef,
      })),
    });
    await ctx.db.patch(original._id, { postingStatus: "reversed", reversalEntryId: rev.entryId });
    await ctx.db.patch(rev.entryId, { reversedEntryId: original._id });
    return true;
  } catch (e) {
    console.error("autoReversePosTicket failed (non-blocking):", String(e));
    return false;
  }
}

async function reversePostedSource(ctx: Ctx, sourceType: string, sourceId: string, reason: string, createdBy?: Id<"users">) {
  const matches = await ctx.db.query("finJournalEntries")
    .withIndex("by_source", (q: any) => q.eq("sourceType", sourceType).eq("sourceId", sourceId)).collect();
  const entry: any = matches.find((e: any) => e.postingStatus === "posted" && !e.reversalEntryId);
  if (!entry) return false;
  const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q: any) => q.eq("entryId", entry._id)).collect();
  const rev = await postEntry(ctx, {
    entryDate: new Date().toISOString().slice(0, 10),
    description: `عكس ${entry.description} — ${reason}`,
    journalType: "reversing",
    isAutoGenerated: true,
    createdBy,
    lines: lines.map((l: any) => ({ accountId: l.accountId, debit: l.credit, credit: l.debit, description: `عكس ${l.description || ""}`, partyType: l.partyType, partyId: l.partyId, documentRef: l.documentRef })),
  });
  await ctx.db.patch(entry._id, { postingStatus: "reversed", reversalEntryId: rev.entryId });
  await ctx.db.patch(rev.entryId, { reversedEntryId: entry._id });
  return true;
}

/** Accrual invoice for an outlet: receivable + discount against gross outlet revenue. */
export async function autoPostGymOrder(ctx: Ctx, orderId: Id<"gymOrders">, createdBy?: Id<"users">): Promise<boolean> {
  try {
    const order: any = await ctx.db.get(orderId);
    if (!order || order.isVoid) return false;
    const matches = await ctx.db.query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "gymOrder").eq("sourceId", String(orderId))).collect();
    if (matches.some((e: any) => e.postingStatus === "posted" && !e.reversalEntryId)) return false;
    const receivable = await accByCode(ctx, "1150");
    const revenue = await accByCode(ctx, "4140");
    const discountAcc = await accByCode(ctx, "4195");
    if (!receivable || !revenue) return false;
    const total = Number(order.total || 0);
    const subtotal = Number(order.subtotal || total);
    const discount = Math.max(0, Number(order.discountAmount || subtotal - total));
    if (total <= 0) return false;
    const lines: LineIn[] = [
      { accountId: receivable, debit: total, description: "ذمة المنفذ", partyType: "outlet", partyId: String(order.gymId), documentRef: String(orderId) },
      { accountId: revenue, credit: subtotal, description: "مبيعات المنفذ", partyType: "outlet", partyId: String(order.gymId), documentRef: String(orderId) },
    ];
    if (discount > 0 && discountAcc) lines.push({ accountId: discountAcc, debit: discount, description: "خصم المنفذ", partyType: "outlet", partyId: String(order.gymId) });
    await postEntry(ctx, { entryDate: order.date, description: `فاتورة منفذ ${String(orderId).slice(-6)}`, lines, journalType: "auto_gym", sourceType: "gymOrder", sourceId: String(orderId), isAutoGenerated: true, createdBy });
    return true;
  } catch (e) {
    console.error("autoPostGymOrder failed (non-blocking):", String(e));
    return false;
  }
}

export async function autoReverseGymOrder(ctx: Ctx, orderId: Id<"gymOrders">, reason: string, createdBy?: Id<"users">) {
  return await reversePostedSource(ctx, "gymOrder", String(orderId), reason, createdBy);
}

/** Outlet returns reduce both the receivable and net sales. */
export async function autoPostGymReturn(ctx: Ctx, returnId: Id<"gymReturnBatches">, createdBy?: Id<"users">): Promise<boolean> {
  try {
    const batch: any = await ctx.db.get(returnId);
    if (!batch || Number(batch.wasteValue || 0) <= 0) return false;
    const existing = await ctx.db.query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "gymReturn").eq("sourceId", String(returnId))).first();
    if (existing) return false;
    const returnsAcc = await accByCode(ctx, "4190");
    const receivable = await accByCode(ctx, "1150");
    if (!returnsAcc || !receivable) return false;
    const amount = Number(batch.wasteValue);
    await postEntry(ctx, {
      entryDate: batch.returnDate,
      description: `مرتجع منفذ ${String(returnId).slice(-6)}`,
      journalType: "auto_gym",
      sourceType: "gymReturn",
      sourceId: String(returnId),
      isAutoGenerated: true,
      createdBy,
      lines: [
        { accountId: returnsAcc, debit: amount, description: "مردودات مبيعات منفذ", partyType: "outlet", partyId: String(batch.gymId), documentRef: String(returnId) },
        { accountId: receivable, credit: amount, description: "تخفيض ذمة المنفذ", partyType: "outlet", partyId: String(batch.gymId), documentRef: String(returnId) },
      ],
    });
    return true;
  } catch (e) {
    console.error("autoPostGymReturn failed (non-blocking):", String(e));
    return false;
  }
}

/** Purchase receipt: inventory asset against supplier payable. */
export async function autoPostInventoryReceipt(ctx: Ctx, opts: { sourceId: string; date: string; amount: number; supplierId?: string; invoiceNo?: string; createdBy?: Id<"users"> }) {
  try {
    if (opts.amount <= 0) return false;
    const existing = await ctx.db.query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "inventoryReceipt").eq("sourceId", opts.sourceId)).first();
    if (existing) return false;
    const inventory = await accByCode(ctx, "1160");
    const payable = await accByCode(ctx, "2110");
    if (!inventory || !payable) return false;
    await postEntry(ctx, {
      entryDate: opts.date, description: `استلام مخزون${opts.invoiceNo ? ` — ${opts.invoiceNo}` : ""}`,
      journalType: "auto_purchase", sourceType: "inventoryReceipt", sourceId: opts.sourceId,
      isAutoGenerated: true, createdBy: opts.createdBy,
      lines: [
        { accountId: inventory, debit: opts.amount, description: "قيمة مواد مستلمة", partyType: "supplier", partyId: opts.supplierId, documentRef: opts.invoiceNo },
        { accountId: payable, credit: opts.amount, description: "ذمة المورد", partyType: "supplier", partyId: opts.supplierId, documentRef: opts.invoiceNo },
      ],
    });
    return true;
  } catch (e) {
    console.error("autoPostInventoryReceipt failed (non-blocking):", String(e));
    return false;
  }
}

/** Inventory issue, waste, or count variance valued at FIFO cost by the inventory module. */
export async function autoPostInventoryMovement(ctx: Ctx, opts: {
  movementId: Id<"inventoryMovements">;
  date: string;
  amount: number;
  kind: "consume" | "waste" | "adjust";
  quantity: number;
  itemId: Id<"inventoryItems">;
  createdBy?: Id<"users">;
}) {
  try {
    if (opts.amount <= 0 || opts.quantity === 0) return false;
    const sourceId = String(opts.movementId);
    const existing = await ctx.db.query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "inventoryMovement").eq("sourceId", sourceId)).first();
    if (existing) return false;
    const inventory = await accByCode(ctx, "1160");
    const expense = await accByCode(ctx, opts.kind === "consume" ? "5110" : opts.kind === "waste" ? "5130" : "5150");
    if (!inventory || !expense) return false;
    const label = opts.kind === "consume" ? "استهلاك مواد المطبخ" : opts.kind === "waste" ? "هالك وتالف مخزون" : "فرق جرد المخزون";
    const increase = opts.kind === "adjust" && opts.quantity > 0;
    await postEntry(ctx, {
      entryDate: opts.date,
      description: label,
      journalType: "auto_inventory",
      sourceType: "inventoryMovement",
      sourceId,
      isAutoGenerated: true,
      createdBy: opts.createdBy,
      lines: increase
        ? [
            { accountId: inventory, debit: opts.amount, description: label, documentRef: String(opts.itemId) },
            { accountId: expense, credit: opts.amount, description: label, documentRef: String(opts.itemId) },
          ]
        : [
            { accountId: expense, debit: opts.amount, description: label, documentRef: String(opts.itemId) },
            { accountId: inventory, credit: opts.amount, description: label, documentRef: String(opts.itemId) },
          ],
    });
    return true;
  } catch (e) {
    console.error("autoPostInventoryMovement failed (non-blocking):", String(e));
    return false;
  }
}

export const postPayrollMonth = mutation({
  args: { month: v.string(), sessionToken: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const actor = await requireFinance(ctx, args.sessionToken);
    if (!/^\d{4}-\d{2}$/.test(args.month)) throw new Error("صيغة الشهر غير صحيحة");
    const existing = await ctx.db.query("finJournalEntries")
      .withIndex("by_source", (q: any) => q.eq("sourceType", "payrollMonth").eq("sourceId", args.month)).collect();
    if (existing.some((entry: any) => entry.postingStatus === "posted" && !entry.reversalEntryId)) {
      throw new Error("رواتب هذا الشهر رُحّلت بالفعل");
    }
    const rows = (await ctx.db.query("payroll").withIndex("by_month", (q: any) => q.eq("month", args.month)).collect()).filter((r: any) => !r.isVoid);
    if (!rows.length) throw new Error("لا توجد رواتب في هذا الشهر");
    let salary = 0, overtime = 0, paid = 0, advance = 0;
    for (const row of rows as any[]) {
      const monthly = (Number(row.basic || 0) + Number(row.allowance || 0)) * Math.min(Number(row.days || 0), 31) / 31;
      salary += Math.round(monthly);
      overtime += Number(row.overtime || 0);
      paid += Number(row.paid || 0);
      advance += Number(row.advance || 0);
    }
    const total = salary + overtime;
    const cashPaid = Math.min(total, paid + advance);
    const accrued = Math.max(0, total - cashPaid);
    const salaryAcc = await accByCode(ctx, "6110");
    const overtimeAcc = await accByCode(ctx, "6115");
    const accruedAcc = await accByCode(ctx, "2120");
    const cashAcc = await accByCode(ctx, "1110");
    if (!salaryAcc || !overtimeAcc || !accruedAcc || !cashAcc) throw new Error("حسابات الرواتب الأساسية غير مكتملة");
    const lines: LineIn[] = [{ accountId: salaryAcc, debit: salary, description: `رواتب ${args.month}` }];
    if (overtime > 0) lines.push({ accountId: overtimeAcc, debit: overtime, description: `إضافي ومكافآت ${args.month}` });
    if (cashPaid > 0) lines.push({ accountId: cashAcc, credit: cashPaid, description: "رواتب وسلف مدفوعة" });
    if (accrued > 0) lines.push({ accountId: accruedAcc, credit: accrued, description: "رواتب مستحقة" });
    const result = await postEntry(ctx, {
      entryDate: `${args.month}-${String(new Date(Number(args.month.slice(0, 4)), Number(args.month.slice(5, 7)), 0).getDate()).padStart(2, "0")}`,
      description: `اعتماد رواتب ${args.month}`,
      lines, journalType: "auto_payroll", sourceType: "payrollMonth", sourceId: args.month,
      isAutoGenerated: true, createdBy: actor.userId as any,
    });
    await auditFinance(ctx, actor, "PAYROLL_MONTH_POSTED", String(result.entryId), { month: args.month, employees: rows.length, total, cashPaid, accrued });
    return { ...result, employees: rows.length, total, cashPaid, accrued };
  },
});

/** Safe, repeatable migration of historical operational documents into the ledger. */
export const reconcileOperationalLedger = mutation({
  args: { sessionToken: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const actor = await requireFinance(ctx, args.sessionToken);
    const result = { posPosted: 0, posReversed: 0, outletsPosted: 0, outletReturnsPosted: 0 };
    const tickets = await ctx.db.query("posTickets").collect();
    for (const ticket of tickets as any[]) {
      if (ticket.status === "PAID" && await autoPostPosTicket(ctx, ticket._id)) result.posPosted++;
      if (["REFUNDED", "VOID"].includes(ticket.status) && await autoReversePosTicket(ctx, ticket._id, "مطابقة تاريخية", actor.userId as any)) result.posReversed++;
    }
    const orders = await ctx.db.query("gymOrders").collect();
    for (const order of orders as any[]) {
      if (!order.isVoid && await autoPostGymOrder(ctx, order._id, actor.userId as any)) result.outletsPosted++;
      if (order.isVoid) await autoReverseGymOrder(ctx, order._id, "طلب ملغى", actor.userId as any);
    }
    const returns = await ctx.db.query("gymReturnBatches").collect();
    for (const batch of returns as any[]) if (await autoPostGymReturn(ctx, batch._id, actor.userId as any)) result.outletReturnsPosted++;
    await auditFinance(ctx, actor, "FINANCE_OPERATIONAL_RECONCILIATION", undefined, result);
    return result;
  },
});

// ترحيل دفعي لكل الفواتير المدفوعة غير المرحّلة (آمن، يُعاد تشغيله).
export const backfillPosTickets = mutation({
  args: { limit: v.optional(v.number()), sessionToken: v.optional(v.string()) },
  handler: async (ctx, args) => {
    await requireFinance(ctx, args.sessionToken);
    const paid = await ctx.db.query("posTickets").withIndex("by_status", (q) => q.eq("status", "PAID")).collect();
    let posted = 0, skipped = 0;
    const lim = args.limit ?? 100000;
    for (const t of paid) {
      if (posted >= lim) break;
      const ok = await autoPostPosTicket(ctx, t._id);
      ok ? posted++ : skipped++;
    }
    return { paidTickets: paid.length, posted, skipped };
  },
});

// ---------- قيد يدوي عام (للمحاسب) ----------
export const createManualEntry = mutation({
  args: {
    entryDate: v.string(),
    description: v.string(),
    journalType: v.optional(v.string()),
    branchId: v.optional(v.id("posBranches")),
    costCenterId: v.optional(v.id("finCostCenters")),
    notes: v.optional(v.string()),
    status: v.optional(v.union(v.literal("draft"), v.literal("posted"))),
    lines: v.array(v.object({
      accountId: v.id("finAccounts"),
      debit: v.optional(v.number()),
      credit: v.optional(v.number()),
      description: v.optional(v.string()),
      costCenterId: v.optional(v.id("finCostCenters")),
      partyType: v.optional(v.string()),
      partyId: v.optional(v.string()),
    })),
    sessionToken: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actor = await requireFinance(ctx, args.sessionToken);
    const result = await postEntry(ctx, {
      entryDate: args.entryDate,
      description: args.description,
      lines: args.lines as any,
      journalType: args.journalType || "general",
      branchId: args.branchId,
      costCenterId: args.costCenterId,
      status: args.status || "posted",
      notes: args.notes,
      isAutoGenerated: false,
      createdBy: actor.userId as any,
    });
    await auditFinance(ctx, actor, "FINANCE_ENTRY_CREATED", String(result.entryId), { entryNumber: result.entryNumber, description: args.description });
    return result;
  },
});

// ---------- تسجيل مصروف سريع (مبسّط للمحاسب) ----------
// مدين: حساب المصروف | دائن: كاش/بنك
export const recordExpense = mutation({
  args: {
    entryDate: v.string(),
    expenseAccountId: v.id("finAccounts"),
    paidFromAccountId: v.id("finAccounts"),
    amount: v.number(),
    description: v.string(),
    costCenterId: v.optional(v.id("finCostCenters")),
    branchId: v.optional(v.id("posBranches")),
    sessionToken: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actor = await requireFinance(ctx, args.sessionToken);
    if (args.amount <= 0) throw new Error("المبلغ يجب أن يكون أكبر من صفر");
    const result = await postEntry(ctx, {
      entryDate: args.entryDate,
      description: args.description,
      journalType: "general",
      branchId: args.branchId,
      costCenterId: args.costCenterId,
      isAutoGenerated: false,
      createdBy: actor.userId as any,
      lines: [
        { accountId: args.expenseAccountId, debit: args.amount, description: args.description },
        { accountId: args.paidFromAccountId, credit: args.amount, description: "سداد" },
      ],
    });
    await auditFinance(ctx, actor, "FINANCE_EXPENSE_RECORDED", String(result.entryId), { amount: args.amount, description: args.description });
    return result;
  },
});

// ---------- عكس قيد مُرحَّل (بدل الحذف — للحفاظ على سجل التدقيق) ----------
export const reverseEntry = mutation({
  args: { entryId: v.id("finJournalEntries"), reason: v.string(), sessionToken: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const actor = await requireFinance(ctx, args.sessionToken);
    const entry: any = await ctx.db.get(args.entryId);
    if (!entry) throw new Error("القيد غير موجود");
    if (entry.postingStatus !== "posted") throw new Error("لا يمكن عكس قيد غير مُرحَّل");
    if (entry.reversalEntryId) throw new Error("القيد معكوس بالفعل");
    const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q) => q.eq("entryId", args.entryId)).collect();
    const today = new Date().toISOString().slice(0, 10);
    const rev = await postEntry(ctx, {
      entryDate: today,
      description: `عكس: ${entry.description} — ${args.reason}`,
      journalType: "reversing",
      branchId: entry.branchId,
      costCenterId: entry.costCenterId,
      isAutoGenerated: false,
      createdBy: actor.userId as any,
      lines: lines.map((l: any) => ({
        accountId: l.accountId,
        debit: l.credit,   // معكوس
        credit: l.debit,
        description: `عكس ${l.description || ""}`,
        costCenterId: l.costCenterId,
        partyType: l.partyType,
        partyId: l.partyId,
      })),
    });
    await ctx.db.patch(entry._id, { postingStatus: "reversed", reversalEntryId: rev.entryId });
    await ctx.db.patch(rev.entryId, { reversedEntryId: entry._id });
    await auditFinance(ctx, actor, "FINANCE_ENTRY_REVERSED", String(entry._id), { reversalEntryId: String(rev.entryId), reason: args.reason });
    return rev;
  },
});

// ---------- استعلام: القيود (مع فلاتر) ----------
export const listJournalEntries = query({
  args: { limit: v.optional(v.number()), fromDate: v.optional(v.string()), toDate: v.optional(v.string()), sessionToken: v.optional(v.string()) },
  handler: async (ctx, args) => {
    await requireFinance(ctx, args.sessionToken);
    let entries = await ctx.db.query("finJournalEntries").withIndex("by_date").order("desc").collect();
    if (args.fromDate) entries = entries.filter((e) => e.entryDate >= args.fromDate!);
    if (args.toDate) entries = entries.filter((e) => e.entryDate <= args.toDate!);
    entries = entries.slice(0, args.limit ?? 200);
    // إرفاق الأسطر
    const out = [];
    for (const e of entries) {
      const lines = await ctx.db.query("finJournalLines").withIndex("by_entry", (q) => q.eq("entryId", e._id)).collect();
      out.push({ ...e, lines });
    }
    return out;
  },
});
