/**
 * @file convex/fixSchedule.ts
 * @description Fix weeks/days for meals that were missed/mismatched by seedMealSchedule
 * Run once: fixSchedule:run
 */
import { mutation } from "./_generated/server";
import { v } from "convex/values";

// Generated by fix_schedule.py — 13 meals needing correction
const UPDATES: { id: string; weeks: number[]; days: string[]; category: string }[] = [
  { id: "kh71qbemh5gx1g40ccny7dv96180v7gd", weeks: [3], days: ["saturday"], category: "lunch" },
  { id: "kh74xjgj8jf3ngqsy5x6drsmds80v7qz", weeks: [2, 4], days: ["wednesday"], category: "lunch" },
  { id: "kh75bfjg5f8s2amfak75hmxxbx80tp88", weeks: [2, 3, 4], days: ["saturday"], category: "snack" },
  { id: "kh7f754gbeh8yggvmeejc2fq8h80vwce", weeks: [2, 4], days: ["monday"], category: "lunch" },
  { id: "kh7amhbcq7sadfhgzzs56jtseh80tf90", weeks: [2, 4], days: ["sunday"], category: "lunch" },
  { id: "kh7dynxcj5n5y5gzn94xwzj2p580vynn", weeks: [2, 3, 4], days: ["tuesday", "wednesday"], category: "snack" },
  { id: "kh7a233rehednv3mev3endnjd580tv9c", weeks: [3], days: ["monday"], category: "breakfast" },
  { id: "kh72x0vd1nnzzj5fswsr0cgh3h80td2y", weeks: [2], days: ["wednesday"], category: "lunch" },
  { id: "kh7bjk19273bma3ke3a1v6mysx80t2dm", weeks: [3], days: ["thursday"], category: "lunch" },
  { id: "kh7e8fzhf089pgg23a6yjwaag980v3rx", weeks: [3], days: ["saturday"], category: "breakfast" },
  { id: "kh71bj1mtx1nzj0fth6qqqf17180tej8", weeks: [3], days: ["saturday"], category: "lunch" },
  // Vegetables Soup — all 4 weeks, Tue/Wed/Thu
  { id: "kh7514q79r9rhzt8zpe7c6vmkd80tyab", weeks: [1, 2, 3, 4], days: ["thursday", "tuesday", "wednesday"], category: "snack" },
  // Mediterranean Feta Salad — all 4 weeks, Thursday
  { id: "kh7dp6fpye2nya1cgcmndqwxyh80xkrs", weeks: [1, 2, 3, 4], days: ["thursday"], category: "snack" },
];

export const run = mutation({
  handler: async (ctx) => {
    let patched = 0;
    for (const u of UPDATES) {
      const meal = await ctx.db.get(u.id as any);
      if (!meal) continue;
      await ctx.db.patch(u.id as any, {
        weeks: u.weeks,
        days: u.days,
        category: u.category as any,
      });
      patched++;
    }
    return { patched };
  },
});
