import { useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/../../convex/_generated/api";
import { useStore } from "@/lib/store";
import { useLanguage } from "@/lib/i18n";
import { Check, Clock3, MessageCircle, Phone, Plus, Save, Search, Send, ShieldCheck, TestTube2, WifiOff } from "lucide-react";
import { buildWhatsAppLink } from "@/lib/whatsapp";
import { matchesSearchQuery } from "@/lib/search";

export default function CustomerCrm() {
 const {sessionToken}=useStore(); const {language}=useLanguage(); const ar=language==="ar"; const t=(a:string,e:string)=>ar?a:e;
 const data:any=useQuery(api.crm.workspace,{sessionToken:sessionToken||undefined}); const create=useMutation(api.crm.createFollowUp); const close=useMutation(api.crm.closeFollowUp);
 const automation:any=useQuery(api.crm.automationSettings,{sessionToken:sessionToken||undefined});
 const automationLogs:any[]=useQuery(api.crm.automationLogs,{limit:30,sessionToken:sessionToken||undefined})||[];
 const [q,setQ]=useState(""); const [note,setNote]=useState(""); const [customer,setCustomer]=useState<any>(null); const [type,setType]=useState<"RENEWAL"|"DELIVERY_FAILURE"|"GENERAL">("GENERAL");
 const soon=useMemo(()=>!data?[]:data.customers.filter((c:any)=>{const d=new Date(c.endDate); const now=new Date(); return c.isActive&&d>=now&&d.getTime()-now.getTime()<=7*86400000;}),[data]);
 const customers=useMemo(()=>!data?[]:data.customers.filter((c:any)=>matchesSearchQuery(q,c.fullName,c.phone)).slice(0,20),[data,q]);
 const add=async()=>{if(!customer||!note.trim())return; await create({customerId:customer._id,type,note,dueDate:undefined,sessionToken:sessionToken||undefined});setNote("");setCustomer(null)};
 const wa=(c:any, text:string)=>{const link=buildWhatsAppLink(c.phone,text); if(link) window.open(link,"_blank","noopener,noreferrer")};
 return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6" dir={ar?"rtl":"ltr"}><header className="rounded-2xl bg-[#0e2a4a] p-6 text-white"><h1 className="text-2xl font-black">{t("متابعة العملاء", "Customer follow-up")}</h1><p className="mt-1 text-sm text-cyan-100">{t("التجديدات، ملاحظات التواصل، وحالات فشل التوصيل في مكان واحد.", "Renewals, contact notes, and failed deliveries in one place.")}</p></header>
 <AutomationPanel settings={automation} logs={automationLogs} sessionToken={sessionToken} t={t} ar={ar}/>
 <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border bg-white p-5"><h2 className="font-black">{t("إنشاء متابعة", "Create follow-up")}</h2><div className="relative mt-4"><Search className="absolute start-3 top-3 h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t("ابحث بالاسم أو الهاتف", "Search name or phone")} className="h-10 w-full rounded-xl border ps-9 pe-3 text-sm"/></div>{q&&<div className="mt-2 max-h-44 overflow-auto rounded-xl border">{customers.map((c:any)=><button key={c._id} onClick={()=>{setCustomer(c);setQ(c.fullName)}} className="block w-full border-b p-3 text-start text-sm hover:bg-cyan-50"><b>{c.fullName}</b><span className="ms-2 text-slate-400">{c.phone}</span></button>)}</div>}<div className="mt-3 flex flex-wrap gap-2">{([{v:'GENERAL',l:t('عام','General')},{v:'RENEWAL',l:t('تجديد','Renewal')},{v:'DELIVERY_FAILURE',l:t('فشل توصيل','Delivery failure')}] as {v:"RENEWAL"|"DELIVERY_FAILURE"|"GENERAL";l:string}[]).map(({v,l})=><button key={v} onClick={()=>setType(v)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${type===v?'bg-cyan-600 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t("ما المطلوب من الفريق؟", "What needs to happen?")} className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm"/><button disabled={!customer||!note.trim()} onClick={add} className="mt-3 flex items-center gap-2 rounded-xl bg-[#0e76ac] px-4 py-2 text-sm font-black text-white disabled:opacity-40"><Plus className="h-4 w-4"/>{t("إضافة متابعة", "Add follow-up")}</button></section>
 <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">{t("المتابعات المفتوحة", "Open follow-ups")}</h2></div><div className="divide-y">{data?.tasks?.length?data.tasks.map((x:any)=><div key={x._id} className="p-4"><p className="font-bold text-slate-800">{x.note}</p><p className="mt-1 text-xs text-slate-400">{x.type}</p><div className="mt-2 flex gap-2"><button onClick={()=>close({id:x._id,status:'DONE',sessionToken:sessionToken||undefined})} className="flex items-center gap-1 text-xs font-black text-emerald-700"><Check className="h-3.5 w-3.5"/>{t("تم", "Done")}</button></div></div>):<p className="p-8 text-center text-sm text-slate-400">{t("لا توجد متابعات", "No open follow-ups")}</p>}</div></section></div>
 <div className="grid gap-5 lg:grid-cols-2"><List title={t("تجديدات قريبة", "Upcoming renewals")} rows={soon} empty={t("لا توجد تجديدات قريبة", "No upcoming renewals")} render={(c:any)=><CustomerRow c={c} text={t(`مرحبًا ${c.fullName}، اشتراكك ينتهي بتاريخ ${c.endDate}. يسعدنا مساعدتك في التجديد.`,`Hi ${c.fullName}, your subscription ends on ${c.endDate}. We would be happy to help you renew.`)} wa={wa} t={t}/>} /><List title={t("حالات فشل التوصيل", "Failed delivery cases")} rows={data?.failedDeliveries||[]} empty={t("لا توجد حالات", "No cases")} render={(p:any)=><CustomerRow c={p.customer} text={t(`مرحبًا ${p.customer?.fullName||''}، نعتذر عن تعذر التوصيل اليوم. نود ترتيب أفضل وقت بديل.`,`Hi ${p.customer?.fullName||''}, sorry we could not complete today's delivery. Let's arrange a suitable alternative.`)} wa={wa} t={t} extra={p.failReason}/>} /></div></div>;
}
function List({title,rows,empty,render}:any){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">{title}</h2></div><div className="divide-y">{rows.length?rows.map((r:any)=><div key={r._id}>{render(r)}</div>):<p className="p-8 text-center text-sm text-slate-400">{empty}</p>}</div></section>}
function CustomerRow({c,text,wa,t,extra}:any){if(!c)return null;return <div className="flex items-center gap-3 p-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-cyan-50 font-black text-cyan-700">{c.fullName?.[0]}</div><div className="min-w-0 flex-1"><b className="block truncate">{c.fullName}</b><span className="text-xs text-slate-400">{extra||c.endDate||c.phone}</span></div><a href={`tel:${c.phone}`} className="text-slate-500"><Phone className="h-4 w-4"/></a><button onClick={()=>wa(c,text)} className="text-emerald-600"><MessageCircle className="h-4 w-4"/></button></div>}

function AutomationPanel({settings,logs,sessionToken,t,ar}:any){
 const save=useMutation(api.crm.saveAutomationSettings); const simulate=useMutation(api.crm.simulateAutomation);
 const [draft,setDraft]=useState<any>(null); const [busy,setBusy]=useState(false); const [saved,setSaved]=useState(false);
 const form=draft||settings;
 if(!form)return <div className="h-32 animate-pulse rounded-2xl bg-slate-100"/>;
 const set=(key:string,value:any)=>{setDraft({...form,[key]:value});setSaved(false)};
 const persist=async()=>{setBusy(true);try{const {connected,hasWebhookSecret,_id,_creationTime,channel,updatedBy,updatedAt,...payload}=form;void connected;void hasWebhookSecret;void _id;void _creationTime;void channel;void updatedBy;void updatedAt;await save({...payload,sessionToken:sessionToken||undefined});setSaved(true);setDraft(null)}finally{setBusy(false)}};
 const events=[
  ["renewal7Enabled",t("قبل الانتهاء بـ7 أيام","7 days before expiry")],
  ["renewal3Enabled",t("قبل الانتهاء بـ3 أيام","3 days before expiry")],
  ["expiryDayEnabled",t("يوم انتهاء الاشتراك","On expiry day")],
  ["expired2Enabled",t("بعد الانتهاء بيومين","2 days after expiry")],
  ["deliveryFailureEnabled",t("عند فشل التوصيل","When delivery fails")],
 ];
 return <section className="overflow-hidden rounded-2xl border border-emerald-200 bg-white shadow-[0_12px_40px_-28px_rgba(5,150,105,.45)]">
  <div className="flex flex-col gap-4 bg-gradient-to-l from-[#073b36] via-[#075e54] to-[#128c7e] p-5 text-white sm:flex-row sm:items-center">
   <div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/15 ring-1 ring-white/25"><Send className="h-5 w-5"/></div>
   <div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{t("رسائل واتساب التلقائية","WhatsApp automation")}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-black ${form.connected?"bg-emerald-300 text-emerald-950":"bg-amber-300 text-amber-950"}`}>{form.connected?t("متصل","Connected"):t("بانتظار الربط","Setup required")}</span>{form.testMode&&<span className="rounded-full bg-white/15 px-2 py-1 text-[10px] font-black">{t("وضع تجريبي","Test mode")}</span>}</div><p className="mt-1 text-xs text-emerald-50/85">{t("التوكن يُحفظ في بيئة Convex فقط ولا يظهر لأي مستخدم.","The token stays in Convex environment variables and is never exposed to users.")}</p></div>
   <button onClick={persist} disabled={busy} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-[#075e54] disabled:opacity-60"><Save className="h-4 w-4"/>{saved?t("تم الحفظ","Saved"):t("حفظ الإعدادات","Save settings")}</button>
  </div>
  <div className="grid gap-5 p-5 xl:grid-cols-[.8fr_1.2fr]">
   <div className="space-y-4">
    <div className="grid grid-cols-2 gap-3"><Toggle label={t("تشغيل الأتمتة","Automation enabled")} value={form.enabled} onChange={(v:boolean)=>set("enabled",v)}/><Toggle label={t("الوضع التجريبي","Test mode")} value={form.testMode} onChange={(v:boolean)=>set("testMode",v)}/></div>
    <div className="rounded-xl border bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2"><Clock3 className="h-4 w-4 text-cyan-700"/><b className="text-sm">{t("جدول الإرسال","Sending schedule")}</b></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-600">{t("الساعة","Hour")}<input type="number" min="0" max="23" value={form.sendHour} onChange={e=>set("sendHour",Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border bg-white px-3"/></label><label className="text-xs font-bold text-slate-600">{t("المنطقة الزمنية","Timezone")}<input value={form.timezone} onChange={e=>set("timezone",e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-white px-3" dir="ltr"/></label></div></div>
    <div className="space-y-2">{events.map(([key,label])=><Toggle key={key} label={label} value={form[key]} onChange={(v:boolean)=>set(key,v)}/>)}</div>
    <button onClick={async()=>{setBusy(true);try{await simulate({sessionToken:sessionToken||undefined})}finally{setBusy(false)}}} disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 py-2.5 text-sm font-black text-emerald-800"><TestTube2 className="h-4 w-4"/>{t("تشغيل تجربة بدون إرسال","Run simulation without sending")}</button>
   </div>
   <div className="space-y-4">
    <Template title={t("قالب تذكير التجديد","Renewal reminder template")} arValue={form.templateRenewalAr} enValue={form.templateRenewalEn} onAr={(v:string)=>set("templateRenewalAr",v)} onEn={(v:string)=>set("templateRenewalEn",v)}/>
    <Template title={t("قالب فشل التوصيل","Delivery failure template")} arValue={form.templateDeliveryAr} enValue={form.templateDeliveryEn} onAr={(v:string)=>set("templateDeliveryAr",v)} onEn={(v:string)=>set("templateDeliveryEn",v)}/>
    <div className="rounded-xl border"><div className="flex items-center justify-between border-b p-3"><b className="text-sm">{t("آخر العمليات","Recent activity")}</b>{form.connected?<ShieldCheck className="h-4 w-4 text-emerald-600"/>:<WifiOff className="h-4 w-4 text-amber-600"/>}</div><div className="max-h-52 divide-y overflow-auto">{logs.length?logs.map((x:any)=><div key={x._id} className="flex items-center gap-3 p-3 text-xs"><span className={`h-2 w-2 rounded-full ${x.status==="FAILED"?"bg-red-500":x.status==="SENT"?"bg-emerald-500":"bg-amber-400"}`}/><div className="min-w-0 flex-1"><b className="block truncate">{x.customerName}</b><span className="text-slate-400">{x.eventKey}</span></div><span className="font-black text-slate-500">{x.status}</span></div>):<p className="p-6 text-center text-xs text-slate-400">{t("لا توجد عمليات حتى الآن","No activity yet")}</p>}</div></div>
   </div>
  </div>
 </section>
}
function Toggle({label,value,onChange}:any){return <button type="button" onClick={()=>onChange(!value)} className={`flex min-h-11 items-center justify-between gap-3 rounded-xl border px-3 text-start text-xs font-black transition-colors ${value?"border-emerald-200 bg-emerald-50 text-emerald-900":"border-slate-200 bg-white text-slate-500"}`}><span>{label}</span><span className={`relative h-6 w-11 rounded-full transition-colors ${value?"bg-emerald-500":"bg-slate-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-all ${value?"end-1":"start-1"}`}/></span></button>}
function Template({title,arValue,enValue,onAr,onEn}:any){return <div className="rounded-xl border bg-white p-4"><b className="text-sm">{title}</b><p className="mt-1 text-[11px] text-slate-400">{"{{name}} · {{endDate}}"}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><textarea dir="rtl" value={arValue} onChange={e=>onAr(e.target.value)} className="min-h-24 rounded-xl border bg-slate-50 p-3 text-sm" aria-label="Arabic template"/><textarea dir="ltr" value={enValue} onChange={e=>onEn(e.target.value)} className="min-h-24 rounded-xl border bg-slate-50 p-3 text-sm" aria-label="English template"/></div></div>}
