import { useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/../../convex/_generated/api";
import { useStore } from "@/lib/store";
import { useLanguage } from "@/lib/i18n";
import { Check, MessageCircle, Phone, Plus, Search, Truck } from "lucide-react";
import { buildWhatsAppLink } from "@/lib/whatsapp";

export default function CustomerCrm() {
 const {sessionToken}=useStore(); const {language}=useLanguage(); const ar=language==="ar"; const t=(a:string,e:string)=>ar?a:e;
 const data:any=useQuery(api.crm.workspace,{sessionToken:sessionToken||undefined}); const create=useMutation(api.crm.createFollowUp); const close=useMutation(api.crm.closeFollowUp);
 const [q,setQ]=useState(""); const [note,setNote]=useState(""); const [customer,setCustomer]=useState<any>(null); const [type,setType]=useState<"RENEWAL"|"DELIVERY_FAILURE"|"GENERAL">("GENERAL");
 const soon=useMemo(()=>!data?[]:data.customers.filter((c:any)=>{const d=new Date(c.endDate); const now=new Date(); return c.isActive&&d>=now&&d.getTime()-now.getTime()<=7*86400000;}),[data]);
 const customers=useMemo(()=>!data?[]:data.customers.filter((c:any)=>`${c.fullName} ${c.phone}`.toLowerCase().includes(q.toLowerCase())).slice(0,20),[data,q]);
 const add=async()=>{if(!customer||!note.trim())return; await create({customerId:customer._id,type,note,dueDate:undefined,sessionToken:sessionToken||undefined});setNote("");setCustomer(null)};
 const wa=(c:any, text:string)=>{const link=buildWhatsAppLink(c.phone,text); if(link) window.open(link,"_blank","noopener,noreferrer")};
 return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6" dir={ar?"rtl":"ltr"}><header className="rounded-2xl bg-[#0e2a4a] p-6 text-white"><h1 className="text-2xl font-black">{t("متابعة العملاء", "Customer follow-up")}</h1><p className="mt-1 text-sm text-cyan-100">{t("التجديدات، ملاحظات التواصل، وحالات فشل التوصيل في مكان واحد.", "Renewals, contact notes, and failed deliveries in one place.")}</p></header>
 <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border bg-white p-5"><h2 className="font-black">{t("إنشاء متابعة", "Create follow-up")}</h2><div className="relative mt-4"><Search className="absolute start-3 top-3 h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t("ابحث بالاسم أو الهاتف", "Search name or phone")} className="h-10 w-full rounded-xl border ps-9 pe-3 text-sm"/></div>{q&&<div className="mt-2 max-h-44 overflow-auto rounded-xl border">{customers.map((c:any)=><button key={c._id} onClick={()=>{setCustomer(c);setQ(c.fullName)}} className="block w-full border-b p-3 text-start text-sm hover:bg-cyan-50"><b>{c.fullName}</b><span className="ms-2 text-slate-400">{c.phone}</span></button>)}</div>}<div className="mt-3 flex flex-wrap gap-2">{([{v:'GENERAL',l:t('عام','General')},{v:'RENEWAL',l:t('تجديد','Renewal')},{v:'DELIVERY_FAILURE',l:t('فشل توصيل','Delivery failure')}] as {v:"RENEWAL"|"DELIVERY_FAILURE"|"GENERAL";l:string}[]).map(({v,l})=><button key={v} onClick={()=>setType(v)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${type===v?'bg-cyan-600 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t("ما المطلوب من الفريق؟", "What needs to happen?")} className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm"/><button disabled={!customer||!note.trim()} onClick={add} className="mt-3 flex items-center gap-2 rounded-xl bg-[#0e76ac] px-4 py-2 text-sm font-black text-white disabled:opacity-40"><Plus className="h-4 w-4"/>{t("إضافة متابعة", "Add follow-up")}</button></section>
 <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">{t("المتابعات المفتوحة", "Open follow-ups")}</h2></div><div className="divide-y">{data?.tasks?.length?data.tasks.map((x:any)=><div key={x._id} className="p-4"><p className="font-bold text-slate-800">{x.note}</p><p className="mt-1 text-xs text-slate-400">{x.type}</p><div className="mt-2 flex gap-2"><button onClick={()=>close({id:x._id,status:'DONE',sessionToken:sessionToken||undefined})} className="flex items-center gap-1 text-xs font-black text-emerald-700"><Check className="h-3.5 w-3.5"/>{t("تم", "Done")}</button></div></div>):<p className="p-8 text-center text-sm text-slate-400">{t("لا توجد متابعات", "No open follow-ups")}</p>}</div></section></div>
 <div className="grid gap-5 lg:grid-cols-2"><List title={t("تجديدات قريبة", "Upcoming renewals")} rows={soon} empty={t("لا توجد تجديدات قريبة", "No upcoming renewals")} render={(c:any)=><CustomerRow c={c} text={t(`مرحبًا ${c.fullName}، اشتراكك ينتهي بتاريخ ${c.endDate}. يسعدنا مساعدتك في التجديد.`,`Hi ${c.fullName}, your subscription ends on ${c.endDate}. We would be happy to help you renew.`)} wa={wa} t={t}/>} /><List title={t("حالات فشل التوصيل", "Failed delivery cases")} rows={data?.failedDeliveries||[]} empty={t("لا توجد حالات", "No cases")} render={(p:any)=><CustomerRow c={p.customer} text={t(`مرحبًا ${p.customer?.fullName||''}، نعتذر عن تعذر التوصيل اليوم. نود ترتيب أفضل وقت بديل.`,`Hi ${p.customer?.fullName||''}, sorry we could not complete today's delivery. Let's arrange a suitable alternative.`)} wa={wa} t={t} extra={p.failReason}/>} /></div></div>;
}
function List({title,rows,empty,render}:any){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">{title}</h2></div><div className="divide-y">{rows.length?rows.map((r:any)=><div key={r._id}>{render(r)}</div>):<p className="p-8 text-center text-sm text-slate-400">{empty}</p>}</div></section>}
function CustomerRow({c,text,wa,t,extra}:any){if(!c)return null;return <div className="flex items-center gap-3 p-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-cyan-50 font-black text-cyan-700">{c.fullName?.[0]}</div><div className="min-w-0 flex-1"><b className="block truncate">{c.fullName}</b><span className="text-xs text-slate-400">{extra||c.endDate||c.phone}</span></div><a href={`tel:${c.phone}`} className="text-slate-500"><Phone className="h-4 w-4"/></a><button onClick={()=>wa(c,text)} className="text-emerald-600"><MessageCircle className="h-4 w-4"/></button></div>}
