import { useQuery } from "convex/react";
import { api } from "@/../../convex/_generated/api";
import { useStore } from "@/lib/store";
import { useLanguage } from "@/lib/i18n";
import { Star, Trophy } from "lucide-react";

export default function LoyaltyRatings() {
 const { sessionToken } = useStore(); const { language } = useLanguage(); const ar=language==="ar"; const t=(a:string,e:string)=>ar?a:e;
 const ratings:any[]=useQuery(api.ratings.listAll,{limit:150,sessionToken:sessionToken||undefined})||[]; const summary:any=useQuery(api.ratings.summary,{})||{};
 const customers:any[]=useQuery(api.customers.list,{sessionToken:sessionToken||undefined})||[];
 const top=[...customers].sort((a,b)=>Number(b.loyaltyPoints||0)-Number(a.loyaltyPoints||0)).slice(0,8);
 return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6" dir={ar?"rtl":"ltr"}><header className="rounded-2xl bg-gradient-to-l from-[#0e2a4a] to-[#0e76ac] p-6 text-white"><h1 className="text-2xl font-black">{t("الولاء والتقييمات", "Loyalty & ratings")}</h1><p className="mt-1 text-sm text-cyan-100">{t("صورة واحدة لصوت العميل ونقاطه.", "A single view of customer sentiment and rewards.")}</p></header><div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{t("متوسط التقييم", "Average rating")}</p><p className="mt-2 text-4xl font-black text-amber-500">{summary.avg||"—"} <Star className="inline h-7 w-7 fill-current"/></p></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{t("إجمالي التقييمات", "Total ratings")}</p><p className="mt-2 text-4xl font-black text-[#0e76ac]">{summary.count||0}</p></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{t("تقييمات منخفضة تحتاج مراجعة", "Low ratings to review")}</p><p className="mt-2 text-4xl font-black text-rose-600">{ratings.filter((r:any)=>r.stars<=2).length}</p></article></div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">{t("آخر التقييمات", "Latest ratings")}</h2></div><div className="divide-y">{ratings.length?ratings.map((r:any)=><div key={r._id} className="p-4"><div className="flex justify-between gap-3"><b>{r.mealName}</b><span className="font-black text-amber-500">{"★".repeat(r.stars)}</span></div><p className="mt-1 text-sm text-slate-600">{r.comment||t("بدون تعليق", "No comment")}</p><p className="mt-1 text-xs text-slate-400">{r.customerName}</p></div>):<p className="p-8 text-center text-slate-400">{t("لا توجد تقييمات", "No ratings yet")}</p>}</div></section><section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="flex items-center gap-2 font-black"><Trophy className="h-4 w-4 text-amber-500"/>{t("أعلى أرصدة الولاء", "Top loyalty balances")}</h2></div><div className="divide-y">{top.map((c:any,i:number)=><div key={c._id} className="flex items-center gap-3 p-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-cyan-50 text-xs font-black text-cyan-700">{i+1}</span><b className="flex-1">{c.fullName}</b><span className="font-black text-[#0e76ac]">{c.loyaltyPoints||0} {t("نقطة", "pts")}</span></div>)}</div></section></div></div>;
}
