import assert from 'node:assert/strict';
import { mock } from 'node:test';
mock.timers.enable({apis:['Date'],now:new Date('2026-09-11T12:00:00').getTime()});
import { createRequire } from 'node:module';
const {mergeSmartSuggestions: merge} = createRequire(import.meta.url)('../apps/mobile/src/smartSelection.ts') as typeof import('../apps/mobile/src/smartSelection');
const customer={_id:'fixture',startDate:'2026-09-12',endDate:'2026-09-13',mealsPerDay:1,snacksPerDay:1,avoid:'NO EGG'};
const today='2026-09-11';
const main={_id:'main',nameAr:'اختبار',category:'lunch',schedule:[{week:2,day:'saturday'},{week:2,day:'sunday'}]};
const snack={...main,_id:'snack',category:'salad'};
const egg={...main,_id:'egg',nameEn:'Egg meal'};
const days=['saturday','sunday'].map((day,i)=>({date:`2026-09-${12+i}`,rotationWeek:2,day,picks:[{id:'missing'},{id:'egg'},{id:'main'},{id:'main'},{id:'snack'}]}));
const run=(c=customer,existing:any[]=[],suggestions=days)=>merge(c,2,existing,[main,snack,egg],suggestions,today);
assert.equal(run().length,4);
assert.equal(run().some(p=>p.meal._id==='egg'),false);
const existing=[{meal:main,week:2,day:'saturday'}];
assert.equal(run(customer,existing).length,4);
assert.equal(existing.length,1);
assert.equal(run(customer,[],days.map(d=>({...d,date:'2026-09-20'}))).length,0);
assert.equal(run(customer,[],days.map(d=>({...d,rotationWeek:3}))).length,0);
assert.equal(run({...customer,snacksPerDay:0}).length,2);
assert.equal(run({...customer,mealsPerDay:0,snacksPerDay:0}).length,0);
assert.equal(run(customer,[],[days[1]]).length,0);
assert.equal(run(customer,[],[days[0]]).length,2);
assert.equal(merge(customer,2,[],[main,snack],days,'2026-09-14').length,0);
console.log('Smart merge: 11 checks passed. Fixtures only; no AI calls or orders.');
mock.timers.reset();
