import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import type { Pick } from '../apps/mobile/src/subscriberSelection';
const { pickVerdict, selectionReady, selectionState } = createRequire(import.meta.url)('../apps/mobile/src/subscriberSelection.ts') as typeof import('../apps/mobile/src/subscriberSelection');
const customer = { _id: 'fixture', startDate: '2026-09-12', endDate: '2026-09-13', mealsPerDay: 1, snacksPerDay: 1, avoid: 'NO EGG' };
const today = '2026-09-11';
const meal = { _id: 'main', nameAr: 'وجبة اختبار', category: 'lunch', schedule: [{ week: 2, day: 'saturday' }, { week: 2, day: 'sunday' }] };
const snack = { ...meal, _id: 'snack', category: 'salad' };
const picks: Pick[] = [];
assert.equal(pickVerdict(customer, 2, picks, 2, 'sunday', meal, today).block, 'previousDayIncomplete');
assert.equal(pickVerdict(customer, 2, picks, 1, 'saturday', meal, today).block, 'outsideSubscription');
assert.equal(pickVerdict(customer, 2, picks, 2, 'saturday', { ...meal, schedule: [] }, today).block, 'unavailable');
picks.push({ meal, week: 2, day: 'saturday' });
assert.equal(pickVerdict(customer, 2, picks, 2, 'saturday', meal, today).block, 'mealsFull');
assert.equal(selectionReady(customer, 2, picks, today), false);
picks.push({ meal: snack, week: 2, day: 'saturday' });
assert.equal(selectionState(customer, 2, picks, today).firstIncomplete, 1);
assert.equal(pickVerdict(customer, 2, picks, 2, 'sunday', meal, today).block, null);
assert.equal(pickVerdict({ ...customer, snacksPerDay: 0 }, 2, [], 2, 'saturday', snack, today).block, 'snacksFull');
assert.equal(pickVerdict(customer, 2, [], 2, 'saturday', { ...meal, nameEn: 'Egg meal' }, today).restriction, 'egg');
const double = { ...customer, mealsPerDay: 2 };
assert.equal(pickVerdict(double, 2, picks, 2, 'saturday', meal, today).duplicate, true);
const breakfast = { ...meal, category: 'breakfast' };
assert.equal(pickVerdict(double, 2, [{ meal: breakfast, week: 2, day: 'saturday' }], 2, 'saturday', breakfast, today).secondBreakfast, true);
picks.push({ meal, week: 2, day: 'sunday' }, { meal: snack, week: 2, day: 'sunday' });
assert.equal(selectionReady(customer, 2, picks, today), true);
assert.equal(selectionReady(customer, 2, [...picks, picks[0]], today), false);
assert.equal(selectionReady(customer, 2, picks, '2026-09-14'), false);
assert.equal(selectionState(customer, 2, picks.slice(1), today).firstIncomplete, 0);
console.log('Native selection: 15 assertions passed; fixtures only, no backend writes.');
